//
// Hardware-free tests for the reactive pose law (control/ReactiveLaw.h) and
// the pose-target source. No robot, no sessions, no Pinocchio. Includes
// cross-validation against the Python simulation law: reactive_fixtures.h
// holds inputs and expected outputs generated by
// scripts/gen_reactive_fixtures.py from the ACTUAL simulation controller —
// agreement there is the "equations verified" evidence for the port.
// Returns nonzero on the first failure.
//

#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <thread>

#include <sys/ioctl.h>
#include <sys/stat.h>
#include <unistd.h>

#include "Config.h"
#include "ReactiveLaw.h"
#include "Targets.h"
#include "reactive_fixtures.h"

namespace
{

    int failures = 0;

    void Check(bool ok, const std::string& what)
    {
        if (!ok) {
            std::cout << "FAIL: " << what << "\n";
            ++failures;
        }
    }

    ReactivePoseGains DefaultGains()
    {
        ReactivePoseGains gains;
        gains.kp_position_s_inv = 1.0;
        gains.kp_rotation_s_inv = 1.0;
        gains.kd_position = 0.3;
        gains.kd_rotation = 0.3;
        gains.limit_avoid_gain_s_inv = 1.0;
        gains.dls_lambda = 0.1;
        return gains;
    }

    void TestRotationLog()
    {
        // Identity -> zero vector.
        Check(RotationLog(Eigen::Matrix3d::Identity()).norm() == 0.0,
              "log of identity is zero");

        // A known axis-angle rotation must come back exactly.
        const Eigen::Vector3d axis = Eigen::Vector3d(1.0, -2.0, 0.5).normalized();
        const double angle = 0.7;
        const Eigen::Matrix3d rotation =
            Eigen::AngleAxisd(angle, axis).toRotationMatrix();
        Check((RotationLog(rotation) - (angle * axis)).norm() < 1e-12,
              "log recovers angle * axis");

        // Against Pinocchio's log3 on the fixture rotations (incl. near-pi).
        for (const auto& c : fixtures::kRotationLogCases) {
            Eigen::Matrix3d fixture_rotation;
            for (int r = 0; r < 3; ++r)
                for (int col = 0; col < 3; ++col)
                    fixture_rotation(r, col) = c.rotation[(3 * r) + col];
            const Eigen::Vector3d expected(c.expected[0], c.expected[1], c.expected[2]);
            Check((RotationLog(fixture_rotation) - expected).norm() < 1e-9,
                  "RotationLog matches pin.log3 (angle " +
                      std::to_string(expected.norm()) + " rad)");
        }
    }

    void TestTaskTwistGating()
    {
        const Eigen::Vector3d e_pos(0.1, 0.2, 0.3);
        const Eigen::Vector3d e_rot(-0.1, 0.05, 0.2);
        const Eigen::Vector3d e_v(0.01, -0.02, 0.03);
        const Eigen::Vector3d e_w(0.1, 0.0, -0.1);

        ReactivePoseGains gains = DefaultGains();
        gains.kp_position_s_inv = 2.0;
        gains.kp_rotation_s_inv = 3.0;
        gains.velocity_enabled = false;

        auto twist = TaskTwist(e_pos, e_rot, e_v, e_w, gains);
        Check((twist.head<3>() - 2.0 * e_pos).norm() < 1e-15, "P position term");
        Check((twist.tail<3>() - 3.0 * e_rot).norm() < 1e-15, "P rotation term");

        gains.velocity_enabled = true;
        twist = TaskTwist(e_pos, e_rot, e_v, e_w, gains);
        Check((twist.head<3>() - (2.0 * e_pos + 0.3 * e_v)).norm() < 1e-15,
              "Kd adds the linear-velocity error");
        Check((twist.tail<3>() - (3.0 * e_rot + 0.3 * e_w)).norm() < 1e-15,
              "Kd adds the angular-velocity error");

        gains.position_enabled = false;
        gains.orientation_enabled = false;
        gains.velocity_enabled = false;
        Check(TaskTwist(e_pos, e_rot, e_v, e_w, gains).norm() == 0.0,
              "all terms disabled -> zero twist");
    }

    // Equation 2 (ReactiveLaw.h TwistError), the counterpart of
    // reactive_controller.py twist_error.
    void TestTwistError()
    {
        Eigen::Matrix<double, 6, 1> measured;
        measured << 0.01, -0.02, 0.03, 0.10, 0.00, -0.10;

        // A zero reference twist must reproduce the law exactly as it stood
        // before the reference twist existed: e = -measured, pure damping.
        // This is the regression guard for every existing source, all of
        // which leave the twist at its default.
        const Twist damping_only = TwistError(Twist{}, measured);
        Check((damping_only.linear_m_s + measured.head<3>()).norm() == 0.0,
              "zero reference twist gives exactly -measured (linear)");
        Check((damping_only.angular_rad_s + measured.tail<3>()).norm() == 0.0,
              "zero reference twist gives exactly -measured (angular)");

        // A moving target: both halves are reference minus measured, so the
        // Kd term feeds the commanded velocity forward instead of resisting
        // it. This is what a future orientation policy needs.
        Twist reference;
        reference.linear_m_s = Eigen::Vector3d(0.05, 0.00, -0.01);
        reference.angular_rad_s = Eigen::Vector3d(0.20, -0.30, 0.40);
        const Twist error = TwistError(reference, measured);
        Check((error.linear_m_s -
               (reference.linear_m_s - measured.head<3>()))
                      .norm() < 1e-15,
              "linear twist error is reference minus measured");
        Check((error.angular_rad_s -
               (reference.angular_rad_s - measured.tail<3>()))
                      .norm() < 1e-15,
              "angular twist error is reference minus measured");

        // A target moving exactly as fast as the arm is a zero error: the
        // Kd term contributes nothing and the P term alone closes the pose
        // gap. Under the old hardcoded law this case was unreachable.
        Twist matched;
        matched.linear_m_s = measured.head<3>();
        matched.angular_rad_s = measured.tail<3>();
        const Twist none = TwistError(matched, measured);
        Check(none.linear_m_s.norm() == 0.0 && none.angular_rad_s.norm() == 0.0,
              "a reference twist matching the measurement is zero error");
    }

    // The reference twist reaches the law through PoseReference, and every
    // operator target leaves it zero.
    void TestPoseReferenceTwistDefault()
    {
        PoseReference reference;
        reference.p_desired = Eigen::Vector3d(0.4, 0.1, 0.3);
        Check(reference.twist.linear_m_s.norm() == 0.0 &&
                  reference.twist.angular_rad_s.norm() == 0.0,
              "a PoseReference defaults to a stationary target");
        Check(reference.arrival_eligible,
              "a stationary PoseReference is arrival-eligible by default");

        RobotState state;
        state.q_rad.setZero();
        state.qdot_rad_s.setZero();
        ControllerStatus status;
        PoseTarget target;
        target.p_desired = Eigen::Vector3d(0.4, 0.1, 0.3);
        PoseTargetMailbox mailbox;
        PoseTargetSource source(target.p_desired, target, mailbox);
        const auto served = source.Get(state, 0.001, status);
        Check(served.pose && served.pose->twist.linear_m_s.norm() == 0.0 &&
                  served.pose->twist.angular_rad_s.norm() == 0.0,
              "operator targets command no reference velocity");
    }

    void TestDampedLeastSquares6()
    {
        // Identity-like Jacobian on joints 1-6: undamped solution exact.
        Eigen::Matrix<double, 6, 7> jacobian = Eigen::Matrix<double, 6, 7>::Zero();
        for (int i = 0; i < 6; ++i)
            jacobian(i, i) = 1.0;
        Eigen::Matrix<double, 6, 1> twist;
        twist << 0.1, -0.2, 0.3, 0.05, -0.05, 0.1;

        auto qdot = DampedLeastSquares6(jacobian, twist, 0.0);
        Check((qdot.head<6>() - twist).norm() < 1e-12, "undamped exact on square part");
        Check(std::abs(qdot[6]) < 1e-12, "joint outside the Jacobian stays at zero");

        // Verify against the closed-form definition.
        const double lambda = 0.3;
        Eigen::Matrix<double, 6, 6> jjt = jacobian * jacobian.transpose();
        jjt.diagonal().array() += lambda * lambda;
        Eigen::Matrix<double, 7, 1> reference =
            jacobian.transpose() * jjt.inverse() * twist;
        Check((DampedLeastSquares6(jacobian, twist, lambda) - reference).norm() < 1e-12,
              "matches the closed-form definition");

        // Rank-1 Jacobian: unreachable directions must not blow up.
        Eigen::Matrix<double, 6, 7> singular = Eigen::Matrix<double, 6, 7>::Zero();
        singular(0, 0) = 1.0;
        Eigen::Matrix<double, 6, 1> unreachable = Eigen::Matrix<double, 6, 1>::Zero();
        unreachable[1] = 1.0;
        auto qdot_singular = DampedLeastSquares6(singular, unreachable, 0.1);
        Check(qdot_singular.allFinite(), "singular Jacobian yields finite velocities");
        Check(qdot_singular.norm() < 1e-9, "unreachable direction commands ~zero");
    }

    void TestLimitAvoidance()
    {
        ReactivePoseGains gains = DefaultGains();
        gains.limit_avoid_gain_s_inv = 2.0;
        const double kDeg = M_PI / 180.0;
        Eigen::Matrix<double, 7, 1> limit;
        limit << 0, 126.9 * kDeg, 0, 145.0 * kDeg, 0, 118.0 * kDeg, 0;
        const double zone = 20.0 * kDeg;

        // Zero Jacobian + damping: projector = identity — isolates the
        // objective, exactly as the old centering test did.
        const Eigen::Matrix<double, 6, 7> no_task =
            Eigen::Matrix<double, 6, 7>::Zero();
        Eigen::Matrix<double, 7, 1> q = Eigen::Matrix<double, 7, 1>::Zero();

        // Everywhere inside the zone: EXACTLY zero, including wrapped and
        // multi-turn positions on unbounded joints.
        q << 170 * kDeg, 60 * kDeg, -350 * kDeg, 110 * kDeg, 40 * kDeg,
             -90 * kDeg, 720 * kDeg;
        auto qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(qdot.norm() == 0.0,
              "objective is exactly zero everywhere inside the zones");

        // 10 deg into j4's zone (entry 125): push is inward, k * excess.
        q.setZero();
        q[3] = 135.0 * kDeg;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(std::abs(qdot[3] - (-2.0 * 10.0 * kDeg)) < 1e-12,
              "positive-side push is inward and linear in the excess");
        q[3] = -135.0 * kDeg;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(std::abs(qdot[3] - (2.0 * 10.0 * kDeg)) < 1e-12,
              "negative-side push is inward and linear in the excess");

        // At the limit itself the magnitude is k * zone.
        q.setZero();
        q[5] = 118.0 * kDeg;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(std::abs(qdot[5] - (-2.0 * zone)) < 1e-12,
              "push at the limit equals gain times zone width");

        // Kortex-style wrapped reading: 250 deg = signed -110, in j6's zone.
        q.setZero();
        q[5] = 250.0 * kDeg;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(std::abs(qdot[5] - (2.0 * 12.0 * kDeg)) < 1e-12,
              "objective wraps the position to the nearest turn");

        // Unbounded joints (limit 0) never push, at any position.
        q.setZero();
        q[0] = 359.0 * kDeg;
        q[2] = -2.5;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(qdot.norm() == 0.0, "unbounded joints never push");

        // With an undamped full-rank Jacobian the projected push stays in
        // the Jacobian null space: J * qdot_null = 0.
        gains.dls_lambda = 0.0;
        Eigen::Matrix<double, 6, 7> jacobian;
        for (int r = 0; r < 6; ++r)
            for (int c = 0; c < 7; ++c)
                jacobian(r, c) =
                    std::sin(1.0 + (3.0 * r) + (7.0 * c)) + (r == c ? 2.0 : 0.0);
        q.setZero();
        q[3] = 140.0 * kDeg;
        qdot = LimitAvoidanceVelocity(jacobian, q, limit, zone, gains);
        Check(qdot.norm() > 0.0, "avoidance produces motion inside the zone");
        Check((jacobian * qdot).norm() < (1e-9 * qdot.norm()),
              "projected push lies in the Jacobian null space");

        // SolveReactiveVelocity only adds it when enabled.
        gains = DefaultGains();
        const Eigen::Vector3d zero3 = Eigen::Vector3d::Zero();
        q.setZero();
        q[3] = 140.0 * kDeg;
        gains.null_space_enabled = false;
        auto without = SolveReactiveVelocity(jacobian, zero3, zero3, zero3,
                                             zero3, q, limit, zone, gains);
        Check(without.norm() == 0.0, "null-space disabled -> no avoidance motion");
        gains.null_space_enabled = true;
        auto with = SolveReactiveVelocity(jacobian, zero3, zero3, zero3,
                                          zero3, q, limit, zone, gains);
        Check(with.norm() > 0.0, "null-space enabled -> avoidance motion");
    }

    // The detailed solve exposes the task/null decomposition the status
    // line and CSV report; its parts must sum to exactly the legacy total,
    // and its leak twist must be the Jacobian image of the projected
    // limit-avoidance velocity — the quantity that competes with the task.
    void TestDetailedSolveDecomposition()
    {
        ReactivePoseGains gains = DefaultGains();
        gains.null_space_enabled = true;
        gains.limit_avoid_gain_s_inv = 5.0;

        Eigen::Matrix<double, 6, 7> jacobian;
        for (int r = 0; r < 6; ++r)
            for (int c = 0; c < 7; ++c)
                jacobian(r, c) = std::sin(1.0 + (3.0 * r) + (7.0 * c)) + (r == c ? 2.0 : 0.0);
        const Eigen::Vector3d e_pos(0.05, -0.02, 0.10);
        const Eigen::Vector3d e_rot(0.01, 0.02, -0.03);
        const Eigen::Vector3d e_v(-0.01, 0.00, 0.02);
        const Eigen::Vector3d e_w(0.00, 0.01, 0.00);
        const double kDeg = M_PI / 180.0;
        Eigen::Matrix<double, 7, 1> q = Eigen::Matrix<double, 7, 1>::Zero();
        q[1] = 0.8;
        q[3] = 140.0 * kDeg;
        Eigen::Matrix<double, 7, 1> limit;
        limit << 0, 126.9 * kDeg, 0, 145.0 * kDeg, 0, 118.0 * kDeg, 0;
        const double zone = 20.0 * kDeg;

        const ReactiveSolution detailed = SolveReactiveVelocityDetailed(
            jacobian, e_pos, e_rot, e_v, e_w, q, limit, zone, gains);
        const auto legacy = SolveReactiveVelocity(jacobian, e_pos, e_rot, e_v,
                                                  e_w, q, limit, zone, gains);
        Check((detailed.qdot_task_rad_s + detailed.qdot_null_rad_s - legacy)
                  .norm() < 1e-12,
              "detailed solve parts sum to the legacy total");

        const auto task_only = DampedLeastSquares6(
            jacobian, TaskTwist(e_pos, e_rot, e_v, e_w, gains), gains.dls_lambda);
        Check((detailed.qdot_task_rad_s - task_only).norm() < 1e-12,
              "detailed task part is exactly the DLS task solution");
        const auto null_only =
            LimitAvoidanceVelocity(jacobian, q, limit, zone, gains);
        Check((detailed.qdot_null_rad_s - null_only).norm() < 1e-12,
              "detailed null part is exactly the projected limit-avoidance velocity");
        Check((detailed.leak_twist - jacobian * null_only).norm() < 1e-12,
              "leak twist is the Jacobian image of the projected limit avoidance");
        Check(detailed.leak_twist.norm() > 0.0,
              "damped projector leaks: the leak twist is nonzero");

        gains.null_space_enabled = false;
        const ReactiveSolution disabled = SolveReactiveVelocityDetailed(
            jacobian, e_pos, e_rot, e_v, e_w, q, limit, zone, gains);
        Check(disabled.qdot_null_rad_s.norm() == 0.0,
              "null-space disabled -> zero null part");
        Check(disabled.leak_twist.norm() == 0.0,
              "null-space disabled -> zero leak twist");
        Check((disabled.qdot_task_rad_s -
               SolveReactiveVelocity(jacobian, e_pos, e_rot, e_v, e_w, q,
                                     limit, zone, gains)).norm() < 1e-12,
              "null-space disabled -> task part is the whole solution");
    }

    // The port must compute what the simulation computes: identical inputs
    // through the Python law (fixtures) and this law, identical outputs.
    void TestAgainstSimulationFixtures()
    {
        for (const auto& c : fixtures::kSolveCases) {
            Eigen::Matrix<double, 6, 7> jacobian;
            for (int r = 0; r < 6; ++r)
                for (int col = 0; col < 7; ++col)
                    jacobian(r, col) = c.jacobian[r * 7 + col];
            Eigen::Matrix<double, 7, 1> q, limit;
            for (int i = 0; i < 7; ++i) {
                q[i] = c.q[i];
                limit[i] = c.limit_rad[i];
            }
            ReactivePoseGains gains;
            gains.kp_position_s_inv = c.kp_position_s_inv;
            gains.kp_rotation_s_inv = c.kp_rotation_s_inv;
            gains.kd_position = c.kd_position;
            gains.kd_rotation = c.kd_rotation;
            gains.limit_avoid_gain_s_inv = c.limit_avoid_gain_s_inv;
            gains.dls_lambda = c.dls_lambda;
            gains.position_enabled = c.position_enabled;
            gains.orientation_enabled = c.orientation_enabled;
            gains.velocity_enabled = c.velocity_enabled;
            gains.null_space_enabled = c.null_space_enabled;
            const auto qdot = SolveReactiveVelocity(
                jacobian, Eigen::Vector3d(c.e_pos), Eigen::Vector3d(c.e_rot),
                Eigen::Vector3d(c.e_v), Eigen::Vector3d(c.e_w), q, limit,
                c.zone_rad, gains);
            for (int i = 0; i < 7; ++i)
                Check(std::abs(qdot[i] - c.expected[i]) < c.tolerance,
                      std::string("fixture ") + c.name + " joint " +
                          std::to_string(i));
        }
    }

    void TestParsePoseTarget()
    {
        std::string error;
        const auto target = ParsePoseTarget("0.4 0.1 0.3", error);
        Check(target.has_value(), "three finite base_link coordinates are accepted");
        Check(target && (target->p_desired - Eigen::Vector3d(0.4, 0.1, 0.3)).norm() == 0.0,
              "parsed target keeps metre coordinates");
        Check(target && !target->rotation.has_value(),
              "runtime target is position-only");

        Check(!ParsePoseTarget("0.4 0.1", error).has_value(),
              "too few coordinates are rejected");
        Check(!ParsePoseTarget("0.4 0.1 0.3 trailing", error).has_value(),
              "trailing text is rejected");
        Check(!ParsePoseTarget("0.4 0.1 0.3 0.0", error).has_value(),
              "a fourth coordinate is rejected");
        Check(!ParsePoseTarget("0.4 x 0.3", error).has_value(),
              "malformed coordinate is rejected");
        Check(!ParsePoseTarget("nan 0.1 0.3", error).has_value(),
              "non-finite coordinate is rejected");
        Check(ParsePoseTarget("5.0 -4.0 3.0", error).has_value(),
              "any finite target is accepted without a reach sphere");
        Check(!ParsePoseTarget("inf 0.1 0.3", error).has_value(),
              "infinite coordinate is rejected");

        // 7-field grammar: parses only when orientation targets are on.
        Check(!ParsePoseTarget("0.4 0.1 0.3 0 0 0 1", error).has_value(),
              "7-field line rejected while kAcceptOrientationTargets is false");
        Check(error.find("orientation targets disabled") != std::string::npos,
              "rejection names the disabled gate");
        Check(!ParsePoseTarget("0.4 0.1 0.3 0 0 0 0.5", error).has_value(),
              "non-unit quaternion rejected");
        Check(!ParsePoseTarget("0.4 0.1 0.3 0 0 1", error).has_value(),
              "six fields rejected");
    }

    PoseTarget PositionTarget(double x, double y, double z)
    {
        PoseTarget target;
        target.p_desired = Eigen::Vector3d(x, y, z);
        return target;
    }

    void TestPoseTargetMailbox()
    {
        PoseTargetMailbox mailbox;
        for (int i = 0; i < 8; ++i)
            Check(mailbox.Enqueue(PositionTarget(0.1 * i, 0.0, 0.0)),
                  "mailbox accepts each of its eight entries");
        Check(!mailbox.Enqueue(PositionTarget(0.9, 0.0, 0.0)),
              "mailbox rejects a ninth entry while full");

        for (int i = 0; i < 8; ++i) {
            const auto target = mailbox.TryDequeue();
            Check(target.has_value(), "mailbox returns queued entry");
            Check(target && target->p_desired == Eigen::Vector3d(0.1 * i, 0.0, 0.0),
                  "mailbox preserves FIFO target ordering");
        }
        Check(!mailbox.TryDequeue().has_value(), "mailbox is empty after eight dequeues");
    }

    void TestPoseTargetMailboxConcurrentHandoff()
    {
        constexpr int kTargetCount = 128;
        PoseTargetMailbox mailbox;
        std::thread producer([&mailbox] {
            for (int i = 0; i < kTargetCount; ++i) {
                const PoseTarget target = PositionTarget(0.001 * i, 0.0, 0.0);
                while (!mailbox.Enqueue(target))
                    std::this_thread::yield();
            }
        });

        for (int i = 0; i < kTargetCount; ++i) {
            std::optional<PoseTarget> target;
            while (!(target = mailbox.TryDequeue()))
                std::this_thread::yield();
            Check(target->p_desired == Eigen::Vector3d(0.001 * i, 0.0, 0.0),
                  "concurrent SPSC handoff preserves FIFO ordering");
        }
        producer.join();
    }

    bool WaitFor(const std::atomic<bool>& flag, std::chrono::milliseconds timeout)
    {
        const auto deadline = std::chrono::steady_clock::now() + timeout;
        while (!flag.load(std::memory_order_acquire) &&
               std::chrono::steady_clock::now() < deadline)
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        return flag.load(std::memory_order_acquire);
    }

    bool WaitForPipeDrain(int fd, std::chrono::milliseconds timeout)
    {
        const auto deadline = std::chrono::steady_clock::now() + timeout;
        while (std::chrono::steady_clock::now() < deadline) {
            int bytes_available = -1;
            if (ioctl(fd, FIONREAD, &bytes_available) == 0 && bytes_available == 0)
                return true;
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
        return false;
    }

    bool WriteAll(int fd, const std::string& text)
    {
        std::size_t written = 0;
        while (written < text.size()) {
            const ssize_t result = write(fd, text.data() + written, text.size() - written);
            if (result <= 0)
                return false;
            written += static_cast<std::size_t>(result);
        }
        return true;
    }

    void TestPoseTargetInputHandlesPartialAndCompletePipeLines()
    {
        int partial_pipe[2] = {-1, -1};
        Check(pipe(partial_pipe) == 0, "partial-line test creates a pipe");
        if (partial_pipe[0] >= 0 && partial_pipe[1] >= 0) {
            PoseTargetMailbox mailbox;
            std::atomic<bool> stop{false};
            std::atomic<bool> exited{false};
            std::thread reader([&] {
                RunPoseTargetInputFromFd(mailbox, stop, partial_pipe[0]);
                exited.store(true, std::memory_order_release);
            });

            Check(WriteAll(partial_pipe[1], "0.1 0.2"),
                  "partial line is written while the pipe stays open");
            Check(WaitForPipeDrain(partial_pipe[0], std::chrono::milliseconds(250)),
                  "reader consumes the partial line into its owned buffer");
            stop.store(true, std::memory_order_release);
            Check(WaitFor(exited, std::chrono::milliseconds(250)),
                  "input reader stops while a partial pipe line remains open");

            // Cleanup keeps a failing implementation from leaving a blocked
            // test thread behind: closing the writer supplies EOF.
            close(partial_pipe[1]);
            reader.join();
            close(partial_pipe[0]);
            Check(!mailbox.TryDequeue().has_value(),
                  "unterminated partial input is not activated after stop");
        }

        int complete_pipe[2] = {-1, -1};
        Check(pipe(complete_pipe) == 0, "complete-line test creates a pipe");
        if (complete_pipe[0] >= 0 && complete_pipe[1] >= 0) {
            PoseTargetMailbox mailbox;
            std::atomic<bool> stop{false};
            std::atomic<bool> exited{false};
            std::thread reader([&] {
                RunPoseTargetInputFromFd(mailbox, stop, complete_pipe[0]);
                exited.store(true, std::memory_order_release);
            });

            Check(WriteAll(complete_pipe[1], "0.1 0.2 0.3\n0.2 0.3 0.4\n"),
                  "multiple complete target lines are written to one pipe");
            close(complete_pipe[1]);
            Check(WaitFor(exited, std::chrono::milliseconds(250)),
                  "input reader exits after pipe EOF");
            reader.join();
            close(complete_pipe[0]);

            const auto first = mailbox.TryDequeue();
            const auto second = mailbox.TryDequeue();
            Check(first && first->p_desired == Eigen::Vector3d(0.1, 0.2, 0.3),
                  "first complete pipe line queues its target");
            Check(second && second->p_desired == Eigen::Vector3d(0.2, 0.3, 0.4),
                  "second complete pipe line queues its target");
        }
    }

    void TestPipeInputSurvivesWriterReconnect()
    {
        const std::string pipe_path = "./test_target_pipe_tmp";
        unlink(pipe_path.c_str());
        Check(mkfifo(pipe_path.c_str(), 0600) == 0, "mkfifo succeeds");

        PoseTargetMailbox mailbox;
        std::atomic<bool> stop{false};
        std::thread reader([&] {
            RunPoseTargetInputFromPipe(mailbox, stop, pipe_path);
        });

        // Two independent writer sessions — the Stage 1 EOF failure mode.
        for (int session = 0; session < 2; ++session) {
            std::ofstream writer(pipe_path);   // blocks until reader has the pipe open
            Check(static_cast<bool>(writer), "writer opens pipe");
            writer << "0.1 0.2 0.3\n";
        }                                       // close = EOF for the reader

        // Both targets must arrive despite the intervening EOF.
        Eigen::Vector3d seen[2];
        int received = 0;
        for (int attempt = 0; attempt < 200 && received < 2; ++attempt) {
            if (const auto target = mailbox.TryDequeue())
                seen[received++] = target->p_desired;
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
        Check(received == 2, "targets from both writer sessions arrive");

        stop.store(true);
        const auto join_start = std::chrono::steady_clock::now();
        reader.join();
        Check(std::chrono::steady_clock::now() - join_start
                  < std::chrono::seconds(1), "reader joins promptly on stop");
        unlink(pipe_path.c_str());
    }

    void TestPoseTargetSource()
    {
        RobotState state;
        state.q_rad.setZero();
        state.qdot_rad_s.setZero();
        ControllerStatus status;

        const PoseTarget position_only = PositionTarget(0.1, 0.2, 0.3);
        PoseTargetMailbox mailbox;
        const CartesianMotionLimits test_limits{1.0, 1.0, 1.0};
        constexpr double kTestHoldS = 0.004;
        PoseTargetSource fixed(position_only.p_desired, position_only, mailbox,
                                test_limits, kTestHoldS);
        auto initial = fixed.Get(state, 0.001, status);
        Check(initial.pose &&
                  (initial.pose->p_desired - Eigen::Vector3d(0.1, 0.2, 0.3))
                          .norm() == 0.0,
              "the fixed target is served from the first Get");
        Check(initial.pose && !initial.pose->rotation.has_value(),
              "position-only fixed target commands no orientation");
        Check(initial.pose && initial.pose->sequence == 0,
              "fixed target has sequence zero");
        Check(initial.pose && initial.pose->arrival_eligible,
              "fixed target is eligible for its terminal arrival");

        Check(mailbox.Enqueue(PositionTarget(0.2, 0.3, 0.4)),
              "first live target queues before fixed arrival");
        Check(mailbox.Enqueue(PositionTarget(0.3, 0.4, 0.5)),
              "second live target queues before fixed arrival");
        auto before_arrival = fixed.Get(state, 0.001, status);
        Check(before_arrival.pose && before_arrival.pose->sequence == 0 &&
                  before_arrival.pose->p_desired == Eigen::Vector3d(0.1, 0.2, 0.3),
              "queued targets cannot bypass the fixed target");

        NotifyPoseTargetSourceOnArrivalEdge(fixed, status);
        auto before_arrival_edge = fixed.Get(state, 0.001, status);
        Check(before_arrival_edge.pose && before_arrival_edge.pose->sequence == 0,
              "a non-arrival status does not advance the queued target");
        status.arrived_edge = true;
        NotifyPoseTargetSourceOnArrivalEdge(fixed, status);
        for (int cycle = 0; cycle < 3; ++cycle) {
            const auto dwell = fixed.Get(state, 0.001, status);
            Check(dwell.pose && dwell.pose->sequence == 0 &&
                      dwell.pose->p_desired == Eigen::Vector3d(0.1, 0.2, 0.3),
                  "the reached fixed target holds for the configured dwell");
        }
        auto first_live = fixed.Get(state, 0.001, status);
        Check(first_live.pose && first_live.pose->sequence == 1 &&
                  first_live.pose->p_desired == Eigen::Vector3d(0.1, 0.2, 0.3),
              "one queued target activates after the full arrival dwell");
        Check(first_live.pose && !first_live.pose->arrival_eligible,
              "a moving profile cannot trigger a terminal arrival");
        status.arrived_edge = false;
        bool moving_twist_seen = false;
        Reference first_terminal;
        for (int cycle = 0; cycle < 10000; ++cycle) {
            first_terminal = fixed.Get(state, 0.001, status);
            moving_twist_seen = moving_twist_seen ||
                (first_terminal.pose &&
                 first_terminal.pose->twist.linear_m_s.norm() > 1e-9);
            if (first_terminal.pose && first_terminal.pose->arrival_eligible)
                break;
        }
        Check(moving_twist_seen,
              "the shaped target supplies Cartesian velocity feed-forward");
        Check(first_terminal.pose && first_terminal.pose->sequence == 1 &&
                  (first_terminal.pose->p_desired -
                   Eigen::Vector3d(0.2, 0.3, 0.4)).norm() < 1e-12 &&
                  first_terminal.pose->arrival_eligible,
              "the shaped reference becomes arrival-eligible only at its endpoint");

        status.arrived_edge = true;
        NotifyPoseTargetSourceOnArrivalEdge(fixed, status);
        for (int cycle = 0; cycle < 4; ++cycle)
            fixed.Get(state, 0.001, status);
        auto second_live = fixed.Get(state, 0.001, status);
        Check(second_live.pose && second_live.pose->sequence == 2,
              "each completed dwell activates exactly one queued target");
        status.arrived_edge = true;
        NotifyPoseTargetSourceOnArrivalEdge(fixed, status);
        auto final_hold = fixed.Get(state, 0.001, status);
        Check(final_hold.pose && final_hold.pose->sequence == 2,
              "a moving target ignores a premature arrival notification");

        PoseTargetMailbox late_mailbox;
        PoseTargetSource late_source(position_only.p_desired, position_only,
                                     late_mailbox, test_limits, kTestHoldS);
        late_source.Get(state, 0.001, status);
        late_source.OnArrived();
        for (int cycle = 0; cycle < 4; ++cycle)
            late_source.Get(state, 0.001, status);
        Check(late_mailbox.Enqueue(PositionTarget(0.5, 0.4, 0.3)),
              "target can be queued after an empty arrival");
        auto late_target = late_source.Get(state, 0.001, status);
        Check(late_target.pose && late_target.pose->sequence == 1 &&
                  late_target.pose->p_desired == Eigen::Vector3d(0.1, 0.2, 0.3),
              "empty arrival leaves source ready for a later target");
    }

    void TestPoseTargetSourceStartsAtMeasuredPose()
    {
        RobotState state;
        state.q_rad.setZero();
        state.qdot_rad_s.setZero();
        ControllerStatus status;
        const Eigen::Vector3d startup(0.1, 0.2, 0.3);
        const PoseTarget terminal = PositionTarget(0.4, 0.2, 0.3);
        PoseTargetMailbox mailbox;
        const CartesianMotionLimits limits{1.0, 1.0, 1.0};
        PoseTargetSource source(startup, terminal, mailbox, limits, 0.0);

        const Reference first = source.Get(state, 0.001, status);
        Check(first.pose && first.pose->p_desired == startup,
              "initial reference starts at the measured Cartesian pose");
        Check(first.pose && first.pose->twist.linear_m_s.norm() == 0.0,
              "initial measured-pose reference has zero velocity");
        Check(first.pose && !first.pose->arrival_eligible,
              "distinct startup and terminal poses are not initially arrived");

        bool progressed = false;
        Reference terminal_reference;
        for (int cycle = 0; cycle < 10000; ++cycle) {
            terminal_reference = source.Get(state, 0.001, status);
            if (terminal_reference.pose &&
                terminal_reference.pose->p_desired.x() > startup.x())
                progressed = true;
            if (terminal_reference.pose &&
                terminal_reference.pose->arrival_eligible)
                break;
        }
        Check(progressed,
              "the initial profile progresses away from the measured pose");
        Check(terminal_reference.pose &&
                  terminal_reference.pose->p_desired == terminal.p_desired &&
                  terminal_reference.pose->twist.linear_m_s.norm() == 0.0,
              "the initial profile ends at the configured terminal target");
    }

    // RotationFromRpy documents the R = Rz*Ry*Rx convention used by the
    // retained kinematics utility.
    void TestRotationFromRpy()
    {
        // Rz(yaw) alone: x -> y. Catches a Rx*Ry*Rz transposition.
        const Eigen::Matrix3d rz = RotationFromRpy(0.0, 0.0, M_PI / 2.0);
        Check((rz * Eigen::Vector3d::UnitX() - Eigen::Vector3d::UnitY())
                      .norm() < 1e-12,
              "yaw about +z maps +x to +y");

        // A representative proper rotation remains valid for the utility.
        const Eigen::Matrix3d home =
            RotationFromRpy(M_PI / 2.0, 0.0, M_PI / 2.0);
        Check(std::abs(home.determinant() - 1.0) < 1e-12,
              "representative rpy is a proper rotation");
    }

} // namespace

int main()
{
    Check(UnitRamp(-0.1, 1.0) == 0.0, "null ramp clamps before start");
    Check(std::abs(UnitRamp(0.25, 1.0) - 0.25) < 1e-12,
          "null ramp scales linearly during startup");
    Check(UnitRamp(2.0, 1.0) == 1.0, "null ramp clamps after duration");
    TestRotationLog();
    TestTwistError();
    TestPoseReferenceTwistDefault();
    TestTaskTwistGating();
    TestDampedLeastSquares6();
    TestLimitAvoidance();
    TestDetailedSolveDecomposition();
    TestAgainstSimulationFixtures();
    TestParsePoseTarget();
    TestPoseTargetMailbox();
    TestPoseTargetMailboxConcurrentHandoff();
    TestPoseTargetInputHandlesPartialAndCompletePipeLines();
    TestPipeInputSurvivesWriterReconnect();
    TestRotationFromRpy();
    TestPoseTargetSource();
    TestPoseTargetSourceStartsAtMeasuredPose();

    if (failures == 0) {
        std::cout << "all reactive-law tests passed\n";
        return 0;
    }
    std::cout << failures << " failure(s)\n";
    return 1;
}
