//
// Hardware-free tests for the reactive pose law (control/ReactiveLaw.h) and
// the pose-target source. No robot, no sessions, no Pinocchio. Includes
// cross-validation against the Python simulation law: reactive_fixtures.h
// holds inputs and expected outputs generated by
// scripts/gen_reactive_fixtures.py from the ACTUAL simulation controller —
// agreement there is the "equations verified" evidence for the port.
// Returns nonzero on the first failure.
//

#include <cmath>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <string>

#include "ReactiveLaw.h"
#include "Targets.h"
#include "reactive_fixtures.h"

namespace
{

    int failures = 0;

    void Check(bool ok, const std::string& what)
    {
        if (!ok) {
            std::cout << "FAIL: " << what << "\n";
            ++failures;
        }
    }

    ReactivePoseGains DefaultGains()
    {
        ReactivePoseGains gains;
        gains.kp_position_s_inv = 1.0;
        gains.kp_rotation_s_inv = 1.0;
        gains.kd_position = 0.3;
        gains.kd_rotation = 0.3;
        gains.null_gain_s_inv = 1.0;
        gains.dls_lambda = 0.1;
        return gains;
    }

    void TestRotationLog()
    {
        // Identity -> zero vector.
        Check(RotationLog(Eigen::Matrix3d::Identity()).norm() == 0.0,
              "log of identity is zero");

        // A known axis-angle rotation must come back exactly.
        const Eigen::Vector3d axis = Eigen::Vector3d(1.0, -2.0, 0.5).normalized();
        const double angle = 0.7;
        const Eigen::Matrix3d rotation =
            Eigen::AngleAxisd(angle, axis).toRotationMatrix();
        Check((RotationLog(rotation) - (angle * axis)).norm() < 1e-12,
              "log recovers angle * axis");

        // Against Pinocchio's log3 on the fixture rotations (incl. near-pi).
        for (const auto& c : fixtures::kRotationLogCases) {
            Eigen::Matrix3d fixture_rotation;
            for (int r = 0; r < 3; ++r)
                for (int col = 0; col < 3; ++col)
                    fixture_rotation(r, col) = c.rotation[(3 * r) + col];
            const Eigen::Vector3d expected(c.expected[0], c.expected[1], c.expected[2]);
            Check((RotationLog(fixture_rotation) - expected).norm() < 1e-9,
                  "RotationLog matches pin.log3 (angle " +
                      std::to_string(expected.norm()) + " rad)");
        }
    }

    void TestTaskTwistGating()
    {
        const Eigen::Vector3d e_pos(0.1, 0.2, 0.3);
        const Eigen::Vector3d e_rot(-0.1, 0.05, 0.2);
        const Eigen::Vector3d e_v(0.01, -0.02, 0.03);
        const Eigen::Vector3d e_w(0.1, 0.0, -0.1);

        ReactivePoseGains gains = DefaultGains();
        gains.kp_position_s_inv = 2.0;
        gains.kp_rotation_s_inv = 3.0;
        gains.velocity_enabled = false;

        auto twist = TaskTwist(e_pos, e_rot, e_v, e_w, gains);
        Check((twist.head<3>() - 2.0 * e_pos).norm() < 1e-15, "P position term");
        Check((twist.tail<3>() - 3.0 * e_rot).norm() < 1e-15, "P rotation term");

        gains.velocity_enabled = true;
        twist = TaskTwist(e_pos, e_rot, e_v, e_w, gains);
        Check((twist.head<3>() - (2.0 * e_pos + 0.3 * e_v)).norm() < 1e-15,
              "Kd adds the linear-velocity error");
        Check((twist.tail<3>() - (3.0 * e_rot + 0.3 * e_w)).norm() < 1e-15,
              "Kd adds the angular-velocity error");

        gains.position_enabled = false;
        gains.orientation_enabled = false;
        gains.velocity_enabled = false;
        Check(TaskTwist(e_pos, e_rot, e_v, e_w, gains).norm() == 0.0,
              "all terms disabled -> zero twist");
    }

    // Equation 2 (ReactiveLaw.h TwistError), the counterpart of
    // reactive_controller.py twist_error.
    void TestTwistError()
    {
        Eigen::Matrix<double, 6, 1> measured;
        measured << 0.01, -0.02, 0.03, 0.10, 0.00, -0.10;

        // A zero reference twist must reproduce the law exactly as it stood
        // before the reference twist existed: e = -measured, pure damping.
        // This is the regression guard for every existing source, all of
        // which leave the twist at its default.
        const Twist damping_only = TwistError(Twist{}, measured);
        Check((damping_only.linear_m_s + measured.head<3>()).norm() == 0.0,
              "zero reference twist gives exactly -measured (linear)");
        Check((damping_only.angular_rad_s + measured.tail<3>()).norm() == 0.0,
              "zero reference twist gives exactly -measured (angular)");

        // A moving target: both halves are reference minus measured, so the
        // Kd term feeds the commanded velocity forward instead of resisting
        // it. This is what a future orientation policy needs.
        Twist reference;
        reference.linear_m_s = Eigen::Vector3d(0.05, 0.00, -0.01);
        reference.angular_rad_s = Eigen::Vector3d(0.20, -0.30, 0.40);
        const Twist error = TwistError(reference, measured);
        Check((error.linear_m_s -
               (reference.linear_m_s - measured.head<3>()))
                      .norm() < 1e-15,
              "linear twist error is reference minus measured");
        Check((error.angular_rad_s -
               (reference.angular_rad_s - measured.tail<3>()))
                      .norm() < 1e-15,
              "angular twist error is reference minus measured");

        // A target moving exactly as fast as the arm is a zero error: the
        // Kd term contributes nothing and the P term alone closes the pose
        // gap. Under the old hardcoded law this case was unreachable.
        Twist matched;
        matched.linear_m_s = measured.head<3>();
        matched.angular_rad_s = measured.tail<3>();
        const Twist none = TwistError(matched, measured);
        Check(none.linear_m_s.norm() == 0.0 && none.angular_rad_s.norm() == 0.0,
              "a reference twist matching the measurement is zero error");
    }

    // The reference twist reaches the law through PoseReference, and every
    // operator target leaves it zero.
    void TestPoseReferenceTwistDefault()
    {
        PoseReference reference;
        reference.p_desired = Eigen::Vector3d(0.4, 0.1, 0.3);
        Check(reference.twist.linear_m_s.norm() == 0.0 &&
                  reference.twist.angular_rad_s.norm() == 0.0,
              "a PoseReference defaults to a stationary target");

        RobotState state;
        state.q_rad.setZero();
        state.qdot_rad_s.setZero();
        ControllerStatus status;
        PoseTarget target;
        target.p_desired = Eigen::Vector3d(0.4, 0.1, 0.3);
        PoseTargetSource source(target);
        const auto served = source.Get(state, 0.001, status);
        Check(served.pose && served.pose->twist.linear_m_s.norm() == 0.0 &&
                  served.pose->twist.angular_rad_s.norm() == 0.0,
              "operator targets command no reference velocity");
    }

    void TestDampedLeastSquares6()
    {
        // Identity-like Jacobian on joints 1-6: undamped solution exact.
        Eigen::Matrix<double, 6, 7> jacobian = Eigen::Matrix<double, 6, 7>::Zero();
        for (int i = 0; i < 6; ++i)
            jacobian(i, i) = 1.0;
        Eigen::Matrix<double, 6, 1> twist;
        twist << 0.1, -0.2, 0.3, 0.05, -0.05, 0.1;

        auto qdot = DampedLeastSquares6(jacobian, twist, 0.0);
        Check((qdot.head<6>() - twist).norm() < 1e-12, "undamped exact on square part");
        Check(std::abs(qdot[6]) < 1e-12, "joint outside the Jacobian stays at zero");

        // Verify against the closed-form definition.
        const double lambda = 0.3;
        Eigen::Matrix<double, 6, 6> jjt = jacobian * jacobian.transpose();
        jjt.diagonal().array() += lambda * lambda;
        Eigen::Matrix<double, 7, 1> reference =
            jacobian.transpose() * jjt.inverse() * twist;
        Check((DampedLeastSquares6(jacobian, twist, lambda) - reference).norm() < 1e-12,
              "matches the closed-form definition");

        // Rank-1 Jacobian: unreachable directions must not blow up.
        Eigen::Matrix<double, 6, 7> singular = Eigen::Matrix<double, 6, 7>::Zero();
        singular(0, 0) = 1.0;
        Eigen::Matrix<double, 6, 1> unreachable = Eigen::Matrix<double, 6, 1>::Zero();
        unreachable[1] = 1.0;
        auto qdot_singular = DampedLeastSquares6(singular, unreachable, 0.1);
        Check(qdot_singular.allFinite(), "singular Jacobian yields finite velocities");
        Check(qdot_singular.norm() < 1e-9, "unreachable direction commands ~zero");
    }

    void TestNullSpace()
    {
        ReactivePoseGains gains = DefaultGains();

        // Zero Jacobian + damping: the projector is the identity, so the
        // objective comes through unchanged — isolates the wrap and mask.
        const Eigen::Matrix<double, 6, 7> no_task = Eigen::Matrix<double, 6, 7>::Zero();
        Eigen::Matrix<double, 7, 1> q = Eigen::Matrix<double, 7, 1>::Zero();
        Eigen::Matrix<double, 7, 1> midpoint = Eigen::Matrix<double, 7, 1>::Zero();
        Eigen::Matrix<double, 7, 1> mask;
        mask << 0, 1, 0, 1, 0, 1, 0; // config::kNullCenteringMask

        // Kortex reports 350 deg; the wrap must pull it -10 deg toward 0,
        // not -350 deg the long way round.
        q[1] = 350.0 * M_PI / 180.0;
        auto qdot = NullSpaceVelocity(no_task, q, midpoint, mask, gains);
        Check(std::abs(qdot[1] - (10.0 * M_PI / 180.0)) < 1e-12,
              "centering error wraps to (-pi, pi]");

        // Masked joints never center, however far from the midpoint.
        q.setZero();
        q[0] = 2.0;
        q[2] = -2.5;
        qdot = NullSpaceVelocity(no_task, q, midpoint, mask, gains);
        Check(qdot.norm() == 0.0, "masked (continuous) joints never center");

        // With an undamped full-rank Jacobian the projector annihilates the
        // task space exactly: J * qdot_null = 0.
        gains.dls_lambda = 0.0;
        Eigen::Matrix<double, 6, 7> jacobian;
        // Deterministic full-rank-6 matrix.
        for (int r = 0; r < 6; ++r)
            for (int c = 0; c < 7; ++c)
                jacobian(r, c) = std::sin(1.0 + (3.0 * r) + (7.0 * c)) + (r == c ? 2.0 : 0.0);
        q.setZero();
        q[1] = 0.8;
        q[3] = -1.1;
        qdot = NullSpaceVelocity(jacobian, q, midpoint, mask, gains);
        Check(qdot.norm() > 0.0, "centering produces motion");
        Check((jacobian * qdot).norm() < (1e-9 * qdot.norm()),
              "projected centering lies in the Jacobian null space");

        // SolveReactiveVelocity only adds it when enabled.
        gains = DefaultGains();
        const Eigen::Vector3d zero3 = Eigen::Vector3d::Zero();
        gains.null_space_enabled = false;
        auto without = SolveReactiveVelocity(jacobian, zero3, zero3, zero3, zero3, q,
                                             midpoint, mask, gains);
        Check(without.norm() == 0.0, "null-space disabled -> no centering motion");
        gains.null_space_enabled = true;
        auto with = SolveReactiveVelocity(jacobian, zero3, zero3, zero3, zero3, q,
                                          midpoint, mask, gains);
        Check(with.norm() > 0.0, "null-space enabled -> centering motion");
    }

    // The port must compute what the simulation computes: identical inputs
    // through the Python law (fixtures) and this law, identical outputs.
    void TestAgainstSimulationFixtures()
    {
        for (const auto& c : fixtures::kSolveCases) {
            Eigen::Matrix<double, 6, 7> jacobian;
            for (int r = 0; r < 6; ++r)
                for (int col = 0; col < 7; ++col)
                    jacobian(r, col) = c.jacobian[(7 * r) + col];
            const Eigen::Vector3d e_pos(c.e_pos[0], c.e_pos[1], c.e_pos[2]);
            const Eigen::Vector3d e_rot(c.e_rot[0], c.e_rot[1], c.e_rot[2]);
            const Eigen::Vector3d e_v(c.e_v[0], c.e_v[1], c.e_v[2]);
            const Eigen::Vector3d e_w(c.e_w[0], c.e_w[1], c.e_w[2]);
            Eigen::Matrix<double, 7, 1> q;
            Eigen::Matrix<double, 7, 1> expected;
            for (int i = 0; i < 7; ++i) {
                q[i] = c.q[i];
                expected[i] = c.expected[i];
            }
            Eigen::Matrix<double, 7, 1> midpoint = Eigen::Matrix<double, 7, 1>::Zero();
            Eigen::Matrix<double, 7, 1> mask;
            mask << 0, 1, 0, 1, 0, 1, 0;

            ReactivePoseGains gains;
            gains.kp_position_s_inv = c.kp_position_s_inv;
            gains.kp_rotation_s_inv = c.kp_rotation_s_inv;
            gains.kd_position = c.kd_position;
            gains.kd_rotation = c.kd_rotation;
            gains.null_gain_s_inv = c.null_gain_s_inv;
            gains.dls_lambda = c.dls_lambda;
            gains.position_enabled = c.position_enabled;
            gains.orientation_enabled = c.orientation_enabled;
            gains.velocity_enabled = c.velocity_enabled;
            gains.null_space_enabled = c.null_space_enabled;

            const auto qdot = SolveReactiveVelocity(jacobian, e_pos, e_rot, e_v, e_w,
                                                    q, midpoint, mask, gains);
            Check((qdot - expected).norm() < c.tolerance,
                  std::string("matches the Python simulation law: ") + c.name);
        }
    }

    void TestPoseTargetSource()
    {
        RobotState state;
        state.q_rad.setZero();
        state.qdot_rad_s.setZero();
        ControllerStatus status;

        // The fixed target applies from the first cycle.
        // Position-only form: an empty rotation leaves the takeover
        // orientation to the controller.
        PoseTarget position_only;
        position_only.p_desired = Eigen::Vector3d(0.1, 0.2, 0.3);
        PoseTargetSource fixed(position_only);
        auto initial = fixed.Get(state, 0.001, status);
        Check(initial.pose &&
                  (initial.pose->p_desired - Eigen::Vector3d(0.1, 0.2, 0.3))
                          .norm() == 0.0,
              "the fixed target is served from the first Get");
        Check(initial.pose && !initial.pose->rotation.has_value(),
              "position-only fixed target commands no orientation");

        // With an rpy configured (Config.h kFixedTargetUseRpy), the same
        // path carries the orientation through to the reference.
        PoseTarget with_rpy;
        with_rpy.p_desired = Eigen::Vector3d(0.1, 0.2, 0.3);
        with_rpy.rotation = RotationFromRpy(0.0, 1.6, 0.8);
        PoseTargetSource oriented(with_rpy);
        auto initial_rpy = oriented.Get(state, 0.001, status);
        Check(initial_rpy.pose && initial_rpy.pose->rotation.has_value(),
              "fixed target with rpy commands an orientation");
        Check(initial_rpy.pose && initial_rpy.pose->rotation &&
                  (*initial_rpy.pose->rotation -
                   RotationFromRpy(0.0, 1.6, 0.8))
                          .norm() < 1e-12,
              "the commanded orientation is the configured rpy");
    }

    // RotationFromRpy is the one place R = Rz*Ry*Rx is written down, and
    // the compiled target goes through it.
    void TestRotationFromRpy()
    {
        // Rz(yaw) alone: x -> y. Catches a Rx*Ry*Rz transposition.
        const Eigen::Matrix3d rz = RotationFromRpy(0.0, 0.0, M_PI / 2.0);
        Check((rz * Eigen::Vector3d::UnitX() - Eigen::Vector3d::UnitY())
                      .norm() < 1e-12,
              "yaw about +z maps +x to +y");

        // The Home orientation used as the kFixedTargetRpyRad default.
        const Eigen::Matrix3d home =
            RotationFromRpy(M_PI / 2.0, 0.0, M_PI / 2.0);
        Check(std::abs(home.determinant() - 1.0) < 1e-12,
              "the Home rpy default is a proper rotation");
    }

} // namespace

int main()
{
    Check(UnitRamp(-0.1, 1.0) == 0.0, "null ramp clamps before start");
    Check(std::abs(UnitRamp(0.25, 1.0) - 0.25) < 1e-12,
          "null ramp scales linearly during startup");
    Check(UnitRamp(2.0, 1.0) == 1.0, "null ramp clamps after duration");
    TestRotationLog();
    TestTwistError();
    TestPoseReferenceTwistDefault();
    TestTaskTwistGating();
    TestDampedLeastSquares6();
    TestNullSpace();
    TestAgainstSimulationFixtures();
    TestRotationFromRpy();
    TestPoseTargetSource();

    if (failures == 0) {
        std::cout << "all reactive-law tests passed\n";
        return 0;
    }
    std::cout << failures << " failure(s)\n";
    return 1;
}
