//
// Hardware-free tests for the reactive pose law (control/ReactiveLaw.h) and
// the pose-target source. No robot, no sessions, no Pinocchio. Includes
// cross-validation against the Python simulation law: reactive_fixtures.h
// holds inputs and expected outputs generated by
// scripts/gen_reactive_fixtures.py from the ACTUAL simulation controller —
// agreement there is the "equations verified" evidence for the port.
// Returns nonzero on the first failure.
//

#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <thread>

#include <sys/ioctl.h>
#include <sys/stat.h>
#include <unistd.h>

#include "Config.h"
#include "JointTrajectory.h"
#include "ReactiveLaw.h"
#include "Targets.h"
#include "reactive_fixtures.h"

namespace
{

    int failures = 0;

    void Check(bool ok, const std::string& what)
    {
        if (!ok) {
            std::cout << "FAIL: " << what << "\n";
            ++failures;
        }
    }

    ReactivePoseGains DefaultGains()
    {
        ReactivePoseGains gains;
        gains.kp_position_s_inv = 1.0;
        gains.kp_rotation_s_inv = 1.0;
        gains.kd_position = 0.3;
        gains.kd_rotation = 0.3;
        gains.limit_avoid_gain_s_inv = 1.0;
        gains.dls_lambda = 0.1;
        return gains;
    }

    void TestRotationLog()
    {
        // Identity -> zero vector.
        Check(RotationLog(Eigen::Matrix3d::Identity()).norm() == 0.0,
              "log of identity is zero");

        // A known axis-angle rotation must come back exactly.
        const Eigen::Vector3d axis = Eigen::Vector3d(1.0, -2.0, 0.5).normalized();
        const double angle = 0.7;
        const Eigen::Matrix3d rotation =
            Eigen::AngleAxisd(angle, axis).toRotationMatrix();
        Check((RotationLog(rotation) - (angle * axis)).norm() < 1e-12,
              "log recovers angle * axis");

        // Against Pinocchio's log3 on the fixture rotations (incl. near-pi).
        for (const auto& c : fixtures::kRotationLogCases) {
            Eigen::Matrix3d fixture_rotation;
            for (int r = 0; r < 3; ++r)
                for (int col = 0; col < 3; ++col)
                    fixture_rotation(r, col) = c.rotation[(3 * r) + col];
            const Eigen::Vector3d expected(c.expected[0], c.expected[1], c.expected[2]);
            Check((RotationLog(fixture_rotation) - expected).norm() < 1e-9,
                  "RotationLog matches pin.log3 (angle " +
                      std::to_string(expected.norm()) + " rad)");
        }
    }

    void TestTaskTwistGating()
    {
        const Eigen::Vector3d e_pos(0.1, 0.2, 0.3);
        const Eigen::Vector3d e_rot(-0.1, 0.05, 0.2);
        const Eigen::Vector3d e_v(0.01, -0.02, 0.03);
        const Eigen::Vector3d e_w(0.1, 0.0, -0.1);

        ReactivePoseGains gains = DefaultGains();
        gains.kp_position_s_inv = 2.0;
        gains.kp_rotation_s_inv = 3.0;
        gains.velocity_enabled = false;

        auto twist = TaskTwist(e_pos, e_rot, e_v, e_w, gains);
        Check((twist.head<3>() - 2.0 * e_pos).norm() < 1e-15, "P position term");
        Check((twist.tail<3>() - 3.0 * e_rot).norm() < 1e-15, "P rotation term");

        gains.velocity_enabled = true;
        twist = TaskTwist(e_pos, e_rot, e_v, e_w, gains);
        Check((twist.head<3>() - (2.0 * e_pos + 0.3 * e_v)).norm() < 1e-15,
              "Kd adds the linear-velocity error");
        Check((twist.tail<3>() - (3.0 * e_rot + 0.3 * e_w)).norm() < 1e-15,
              "Kd adds the angular-velocity error");

        gains.position_enabled = false;
        gains.orientation_enabled = false;
        gains.velocity_enabled = false;
        Check(TaskTwist(e_pos, e_rot, e_v, e_w, gains).norm() == 0.0,
              "all terms disabled -> zero twist");
    }

    // Equation 2 (ReactiveLaw.h TwistError), the counterpart of
    // reactive_controller.py twist_error.
    void TestTwistError()
    {
        Eigen::Matrix<double, 6, 1> measured;
        measured << 0.01, -0.02, 0.03, 0.10, 0.00, -0.10;

        // A zero reference twist must reproduce the law exactly as it stood
        // before the reference twist existed: e = -measured, pure damping.
        // This is the regression guard for every existing source, all of
        // which leave the twist at its default.
        const Twist damping_only = TwistError(Twist{}, measured);
        Check((damping_only.linear_m_s + measured.head<3>()).norm() == 0.0,
              "zero reference twist gives exactly -measured (linear)");
        Check((damping_only.angular_rad_s + measured.tail<3>()).norm() == 0.0,
              "zero reference twist gives exactly -measured (angular)");

        // A moving target: both halves are reference minus measured, so the
        // Kd term feeds the commanded velocity forward instead of resisting
        // it. This is what a future orientation policy needs.
        Twist reference;
        reference.linear_m_s = Eigen::Vector3d(0.05, 0.00, -0.01);
        reference.angular_rad_s = Eigen::Vector3d(0.20, -0.30, 0.40);
        const Twist error = TwistError(reference, measured);
        Check((error.linear_m_s -
               (reference.linear_m_s - measured.head<3>()))
                      .norm() < 1e-15,
              "linear twist error is reference minus measured");
        Check((error.angular_rad_s -
               (reference.angular_rad_s - measured.tail<3>()))
                      .norm() < 1e-15,
              "angular twist error is reference minus measured");

        // A target moving exactly as fast as the arm is a zero error: the
        // Kd term contributes nothing and the P term alone closes the pose
        // gap. Under the old hardcoded law this case was unreachable.
        Twist matched;
        matched.linear_m_s = measured.head<3>();
        matched.angular_rad_s = measured.tail<3>();
        const Twist none = TwistError(matched, measured);
        Check(none.linear_m_s.norm() == 0.0 && none.angular_rad_s.norm() == 0.0,
              "a reference twist matching the measurement is zero error");
    }

    // The reference twist reaches the law through PoseReference, and every
    // operator target leaves it zero.
    void TestDampedLeastSquares6()
    {
        // Identity-like Jacobian on joints 1-6: undamped solution exact.
        Eigen::Matrix<double, 6, 7> jacobian = Eigen::Matrix<double, 6, 7>::Zero();
        for (int i = 0; i < 6; ++i)
            jacobian(i, i) = 1.0;
        Eigen::Matrix<double, 6, 1> twist;
        twist << 0.1, -0.2, 0.3, 0.05, -0.05, 0.1;

        auto qdot = DampedLeastSquares6(jacobian, twist, 0.0);
        Check((qdot.head<6>() - twist).norm() < 1e-12, "undamped exact on square part");
        Check(std::abs(qdot[6]) < 1e-12, "joint outside the Jacobian stays at zero");

        // Verify against the closed-form definition.
        const double lambda = 0.3;
        Eigen::Matrix<double, 6, 6> jjt = jacobian * jacobian.transpose();
        jjt.diagonal().array() += lambda * lambda;
        Eigen::Matrix<double, 7, 1> reference =
            jacobian.transpose() * jjt.inverse() * twist;
        Check((DampedLeastSquares6(jacobian, twist, lambda) - reference).norm() < 1e-12,
              "matches the closed-form definition");

        // Rank-1 Jacobian: unreachable directions must not blow up.
        Eigen::Matrix<double, 6, 7> singular = Eigen::Matrix<double, 6, 7>::Zero();
        singular(0, 0) = 1.0;
        Eigen::Matrix<double, 6, 1> unreachable = Eigen::Matrix<double, 6, 1>::Zero();
        unreachable[1] = 1.0;
        auto qdot_singular = DampedLeastSquares6(singular, unreachable, 0.1);
        Check(qdot_singular.allFinite(), "singular Jacobian yields finite velocities");
        Check(qdot_singular.norm() < 1e-9, "unreachable direction commands ~zero");
    }

    void TestLimitAvoidance()
    {
        ReactivePoseGains gains = DefaultGains();
        gains.limit_avoid_gain_s_inv = 2.0;
        const double kDeg = M_PI / 180.0;
        Eigen::Matrix<double, 7, 1> limit;
        limit << 0, 126.9 * kDeg, 0, 145.0 * kDeg, 0, 118.0 * kDeg, 0;
        const double zone = 20.0 * kDeg;

        // Zero Jacobian + damping: projector = identity — isolates the
        // objective, exactly as the old centering test did.
        const Eigen::Matrix<double, 6, 7> no_task =
            Eigen::Matrix<double, 6, 7>::Zero();
        Eigen::Matrix<double, 7, 1> q = Eigen::Matrix<double, 7, 1>::Zero();

        // Everywhere inside the zone: EXACTLY zero, including wrapped and
        // multi-turn positions on unbounded joints.
        q << 170 * kDeg, 60 * kDeg, -350 * kDeg, 110 * kDeg, 40 * kDeg,
             -90 * kDeg, 720 * kDeg;
        auto qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(qdot.norm() == 0.0,
              "objective is exactly zero everywhere inside the zones");

        // 10 deg into j4's zone (entry 125): push is inward, k * excess.
        q.setZero();
        q[3] = 135.0 * kDeg;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(std::abs(qdot[3] - (-2.0 * 10.0 * kDeg)) < 1e-12,
              "positive-side push is inward and linear in the excess");
        q[3] = -135.0 * kDeg;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(std::abs(qdot[3] - (2.0 * 10.0 * kDeg)) < 1e-12,
              "negative-side push is inward and linear in the excess");

        // At the limit itself the magnitude is k * zone.
        q.setZero();
        q[5] = 118.0 * kDeg;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(std::abs(qdot[5] - (-2.0 * zone)) < 1e-12,
              "push at the limit equals gain times zone width");

        // Kortex-style wrapped reading: 250 deg = signed -110, in j6's zone.
        q.setZero();
        q[5] = 250.0 * kDeg;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(std::abs(qdot[5] - (2.0 * 12.0 * kDeg)) < 1e-12,
              "objective wraps the position to the nearest turn");

        // Unbounded joints (limit 0) never push, at any position.
        q.setZero();
        q[0] = 359.0 * kDeg;
        q[2] = -2.5;
        qdot = LimitAvoidanceVelocity(no_task, q, limit, zone, gains);
        Check(qdot.norm() == 0.0, "unbounded joints never push");

        // With an undamped full-rank Jacobian the projected push stays in
        // the Jacobian null space: J * qdot_null = 0.
        gains.dls_lambda = 0.0;
        Eigen::Matrix<double, 6, 7> jacobian;
        for (int r = 0; r < 6; ++r)
            for (int c = 0; c < 7; ++c)
                jacobian(r, c) =
                    std::sin(1.0 + (3.0 * r) + (7.0 * c)) + (r == c ? 2.0 : 0.0);
        q.setZero();
        q[3] = 140.0 * kDeg;
        qdot = LimitAvoidanceVelocity(jacobian, q, limit, zone, gains);
        Check(qdot.norm() > 0.0, "avoidance produces motion inside the zone");
        Check((jacobian * qdot).norm() < (1e-9 * qdot.norm()),
              "projected push lies in the Jacobian null space");

        // SolveReactiveVelocity only adds it when enabled.
        gains = DefaultGains();
        const Eigen::Vector3d zero3 = Eigen::Vector3d::Zero();
        q.setZero();
        q[3] = 140.0 * kDeg;
        gains.null_space_enabled = false;
        auto without = SolveReactiveVelocity(jacobian, zero3, zero3, zero3,
                                             zero3, q, limit, zone, gains);
        Check(without.norm() == 0.0, "null-space disabled -> no avoidance motion");
        gains.null_space_enabled = true;
        auto with = SolveReactiveVelocity(jacobian, zero3, zero3, zero3,
                                          zero3, q, limit, zone, gains);
        Check(with.norm() > 0.0, "null-space enabled -> avoidance motion");
    }

    // The detailed solve exposes the task/null decomposition the status
    // line and CSV report; its parts must sum to exactly the legacy total,
    // and its leak twist must be the Jacobian image of the projected
    // limit-avoidance velocity — the quantity that competes with the task.
    void TestDetailedSolveDecomposition()
    {
        ReactivePoseGains gains = DefaultGains();
        gains.null_space_enabled = true;
        gains.limit_avoid_gain_s_inv = 5.0;

        Eigen::Matrix<double, 6, 7> jacobian;
        for (int r = 0; r < 6; ++r)
            for (int c = 0; c < 7; ++c)
                jacobian(r, c) = std::sin(1.0 + (3.0 * r) + (7.0 * c)) + (r == c ? 2.0 : 0.0);
        const Eigen::Vector3d e_pos(0.05, -0.02, 0.10);
        const Eigen::Vector3d e_rot(0.01, 0.02, -0.03);
        const Eigen::Vector3d e_v(-0.01, 0.00, 0.02);
        const Eigen::Vector3d e_w(0.00, 0.01, 0.00);
        const double kDeg = M_PI / 180.0;
        Eigen::Matrix<double, 7, 1> q = Eigen::Matrix<double, 7, 1>::Zero();
        q[1] = 0.8;
        q[3] = 140.0 * kDeg;
        Eigen::Matrix<double, 7, 1> limit;
        limit << 0, 126.9 * kDeg, 0, 145.0 * kDeg, 0, 118.0 * kDeg, 0;
        const double zone = 20.0 * kDeg;

        const ReactiveSolution detailed = SolveReactiveVelocityDetailed(
            jacobian, e_pos, e_rot, e_v, e_w, q, limit, zone, gains);
        const auto legacy = SolveReactiveVelocity(jacobian, e_pos, e_rot, e_v,
                                                  e_w, q, limit, zone, gains);
        Check((detailed.qdot_task_rad_s + detailed.qdot_null_rad_s - legacy)
                  .norm() < 1e-12,
              "detailed solve parts sum to the legacy total");

        const auto task_only = DampedLeastSquares6(
            jacobian, TaskTwist(e_pos, e_rot, e_v, e_w, gains), gains.dls_lambda);
        Check((detailed.qdot_task_rad_s - task_only).norm() < 1e-12,
              "detailed task part is exactly the DLS task solution");
        const auto null_only =
            LimitAvoidanceVelocity(jacobian, q, limit, zone, gains);
        Check((detailed.qdot_null_rad_s - null_only).norm() < 1e-12,
              "detailed null part is exactly the projected limit-avoidance velocity");
        Check((detailed.leak_twist - jacobian * null_only).norm() < 1e-12,
              "leak twist is the Jacobian image of the projected limit avoidance");
        Check(detailed.leak_twist.norm() > 0.0,
              "damped projector leaks: the leak twist is nonzero");

        gains.null_space_enabled = false;
        const ReactiveSolution disabled = SolveReactiveVelocityDetailed(
            jacobian, e_pos, e_rot, e_v, e_w, q, limit, zone, gains);
        Check(disabled.qdot_null_rad_s.norm() == 0.0,
              "null-space disabled -> zero null part");
        Check(disabled.leak_twist.norm() == 0.0,
              "null-space disabled -> zero leak twist");
        Check((disabled.qdot_task_rad_s -
               SolveReactiveVelocity(jacobian, e_pos, e_rot, e_v, e_w, q,
                                     limit, zone, gains)).norm() < 1e-12,
              "null-space disabled -> task part is the whole solution");
    }

    // Slice 1 of the world-frame architecture: a nominal joint state
    // (q_nom, qdot_nom) may enter the null space as a SECONDARY objective,
    //     qdot_nom + kq · wrap(q_nom − q),
    // summed with the limit-avoidance objective and projected once. The
    // task solution must be untouched, absence of a nominal must reproduce
    // the pre-slice law exactly, and bad guidance must degrade to no
    // guidance rather than a NaN command.
    void TestPostureGuidance()
    {
        const double kDeg = M_PI / 180.0;
        ReactivePoseGains gains = DefaultGains();
        gains.null_space_enabled = true;
        gains.posture_enabled = true;
        gains.posture_gain_s_inv = 0.5;

        Eigen::Matrix<double, 7, 1> limit;
        limit << 0, 126.9 * kDeg, 0, 145.0 * kDeg, 0, 118.0 * kDeg, 0;
        const double zone = 20.0 * kDeg;

        // A configuration with every bounded joint inside its zone, so the
        // limit-avoidance objective is exactly zero and only posture acts.
        Eigen::Matrix<double, 7, 1> q;
        q << 0.3, 0.4, -0.2, 0.9, 0.1, -0.5, 1.2;

        // At the nominal, with zero nominal velocity: exactly zero objective.
        JointReference nominal;
        nominal.q_rad = q;
        nominal.qdot_rad_s.setZero();
        Check(PostureObjective(q, nominal, gains).norm() == 0.0,
              "posture objective is exactly zero at the nominal");

        // 10 deg away on j2: the pull is kq * error, toward the nominal.
        nominal.q_rad[1] = q[1] + 10.0 * kDeg;
        auto objective = PostureObjective(q, nominal, gains);
        Check(std::abs(objective[1] - (0.5 * 10.0 * kDeg)) < 1e-12,
              "posture pull is gain times the error, toward the nominal");
        Check(std::abs(objective[0]) < 1e-15 && std::abs(objective[6]) < 1e-15,
              "joints already at their nominal are not pushed");

        // The nominal velocity feeds forward on top of the pull.
        nominal.qdot_rad_s[1] = 0.2;
        objective = PostureObjective(q, nominal, gains);
        Check(std::abs(objective[1] - (0.2 + 0.5 * 10.0 * kDeg)) < 1e-12,
              "nominal velocity feeds forward on top of the posture pull");

        // Kortex wrap: a nominal of -20 deg with the joint reading 340 deg is
        // the SAME physical angle — near-zero error, not a full-turn pull.
        JointReference wrapped;
        wrapped.q_rad.setConstant(0.0);
        wrapped.qdot_rad_s.setZero();
        Eigen::Matrix<double, 7, 1> q_wrapped =
            Eigen::Matrix<double, 7, 1>::Zero();
        wrapped.q_rad[0] = -20.0 * kDeg;
        q_wrapped[0] = 340.0 * kDeg;
        Check(PostureObjective(q_wrapped, wrapped, gains).norm() < 1e-12,
              "posture error wraps: -20 deg nominal vs 340 deg measured is zero");

        // Disabled -> exactly zero, whatever the error.
        {
            ReactivePoseGains off = gains;
            off.posture_enabled = false;
            Check(PostureObjective(q, nominal, off).norm() == 0.0,
                  "posture disabled -> exactly zero objective");
        }

        // Non-finite guidance degrades to NO guidance, never a NaN command.
        {
            JointReference bad = nominal;
            bad.q_rad[3] = std::numeric_limits<double>::quiet_NaN();
            Check(PostureObjective(q, bad, gains).norm() == 0.0,
                  "non-finite nominal position -> zero objective");
            JointReference bad_vel = nominal;
            bad_vel.qdot_rad_s[2] = std::numeric_limits<double>::infinity();
            Check(PostureObjective(q, bad_vel, gains).norm() == 0.0,
                  "non-finite nominal velocity -> zero objective");
        }

        // Through the detailed solve, against a full-rank Jacobian.
        Eigen::Matrix<double, 6, 7> jacobian;
        for (int r = 0; r < 6; ++r)
            for (int c = 0; c < 7; ++c)
                jacobian(r, c) =
                    std::sin(1.0 + (3.0 * r) + (7.0 * c)) + (r == c ? 2.0 : 0.0);
        const Eigen::Vector3d e_pos(0.05, -0.02, 0.10);
        const Eigen::Vector3d e_rot(0.01, 0.02, -0.03);
        const Eigen::Vector3d zero3 = Eigen::Vector3d::Zero();

        const ReactiveSolution without = SolveReactiveVelocityDetailed(
            jacobian, e_pos, e_rot, zero3, zero3, q, limit, zone, gains);
        const ReactiveSolution with_nominal = SolveReactiveVelocityDetailed(
            jacobian, e_pos, e_rot, zero3, zero3, q, limit, zone, gains,
            &nominal);

        // The PRIMARY task solution is untouched by guidance.
        Check((with_nominal.qdot_task_rad_s - without.qdot_task_rad_s).norm()
                  == 0.0,
              "posture guidance leaves the task solution untouched");

        // The null part is the single projection of the SUMMED objective:
        // limit avoidance (zero here, all joints inside their zones) plus
        // posture.
        const auto expected_null = ProjectToNullSpace(
            jacobian, PostureObjective(q, nominal, gains), gains.dls_lambda);
        Check((with_nominal.qdot_null_rad_s - expected_null).norm() < 1e-12,
              "null part is the projected summed objective");
        Check(with_nominal.qdot_null_rad_s.norm() > 0.0,
              "posture guidance produces null-space motion");

        // Leak accounting covers the enlarged objective.
        Check((with_nominal.leak_twist -
               jacobian * with_nominal.qdot_null_rad_s).norm() < 1e-12,
              "leak twist is the Jacobian image of the whole null command");

        // With an UNDAMPED projector the guidance stays out of task space.
        {
            ReactivePoseGains undamped = gains;
            undamped.dls_lambda = 0.0;
            const auto null_only = ProjectToNullSpace(
                jacobian, PostureObjective(q, nominal, undamped), 0.0);
            Check((jacobian * null_only).norm() < 1e-9 * null_only.norm(),
                  "undamped projected posture lies in the Jacobian null space");
        }

        // No nominal supplied -> IDENTICAL to the pre-slice law, even with
        // the term enabled: the regression guard for every existing caller.
        const ReactiveSolution absent = SolveReactiveVelocityDetailed(
            jacobian, e_pos, e_rot, zero3, zero3, q, limit, zone, gains,
            nullptr);
        Check((absent.qdot_task_rad_s - without.qdot_task_rad_s).norm() == 0.0 &&
              (absent.qdot_null_rad_s - without.qdot_null_rad_s).norm() == 0.0,
              "no nominal supplied reproduces the pre-slice solution exactly");

        // Posture and limit avoidance sum before the one projection.
        Eigen::Matrix<double, 7, 1> q_in_zone = q;
        q_in_zone[3] = 140.0 * kDeg; // 5 deg into j4's zone
        JointReference nominal_zone = nominal;
        nominal_zone.q_rad = q; // pull j4 back toward 0.9 rad
        const ReactiveSolution both = SolveReactiveVelocityDetailed(
            jacobian, e_pos, e_rot, zero3, zero3, q_in_zone, limit, zone,
            gains, &nominal_zone);
        const auto summed = ProjectToNullSpace(
            jacobian,
            LimitAvoidanceObjective(q_in_zone, limit, zone, gains) +
                PostureObjective(q_in_zone, nominal_zone, gains),
            gains.dls_lambda);
        Check((both.qdot_null_rad_s - summed).norm() < 1e-12,
              "limit avoidance and posture sum before the single projection");
    }

    // The port must compute what the simulation computes: identical inputs
    // through the Python law (fixtures) and this law, identical outputs.
    void TestAgainstSimulationFixtures()
    {
        for (const auto& c : fixtures::kSolveCases) {
            Eigen::Matrix<double, 6, 7> jacobian;
            for (int r = 0; r < 6; ++r)
                for (int col = 0; col < 7; ++col)
                    jacobian(r, col) = c.jacobian[r * 7 + col];
            Eigen::Matrix<double, 7, 1> q, limit;
            for (int i = 0; i < 7; ++i) {
                q[i] = c.q[i];
                limit[i] = c.limit_rad[i];
            }
            ReactivePoseGains gains;
            gains.kp_position_s_inv = c.kp_position_s_inv;
            gains.kp_rotation_s_inv = c.kp_rotation_s_inv;
            gains.kd_position = c.kd_position;
            gains.kd_rotation = c.kd_rotation;
            gains.limit_avoid_gain_s_inv = c.limit_avoid_gain_s_inv;
            gains.dls_lambda = c.dls_lambda;
            gains.position_enabled = c.position_enabled;
            gains.orientation_enabled = c.orientation_enabled;
            gains.velocity_enabled = c.velocity_enabled;
            gains.null_space_enabled = c.null_space_enabled;
            const auto qdot = SolveReactiveVelocity(
                jacobian, Eigen::Vector3d(c.e_pos), Eigen::Vector3d(c.e_rot),
                Eigen::Vector3d(c.e_v), Eigen::Vector3d(c.e_w), q, limit,
                c.zone_rad, gains);
            for (int i = 0; i < 7; ++i)
                Check(std::abs(qdot[i] - c.expected[i]) < c.tolerance,
                      std::string("fixture ") + c.name + " joint " +
                          std::to_string(i));
        }
    }

    bool WaitFor(const std::atomic<bool>& flag, std::chrono::milliseconds timeout)
    {
        const auto deadline = std::chrono::steady_clock::now() + timeout;
        while (!flag.load(std::memory_order_acquire) &&
               std::chrono::steady_clock::now() < deadline)
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        return flag.load(std::memory_order_acquire);
    }

    bool WaitForPipeDrain(int fd, std::chrono::milliseconds timeout)
    {
        const auto deadline = std::chrono::steady_clock::now() + timeout;
        while (std::chrono::steady_clock::now() < deadline) {
            int bytes_available = -1;
            if (ioctl(fd, FIONREAD, &bytes_available) == 0 && bytes_available == 0)
                return true;
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
        return false;
    }

    bool WriteAll(int fd, const std::string& text)
    {
        std::size_t written = 0;
        while (written < text.size()) {
            const ssize_t result = write(fd, text.data() + written, text.size() - written);
            if (result <= 0)
                return false;
            written += static_cast<std::size_t>(result);
        }
        return true;
    }

    // A minimal valid block: two rows, all joints at zero, one second apart.
    // Any q inside the compiled limits works — these tests are about the
    // fd-level plumbing (partial lines, EOF, writer reconnect), not the
    // trajectory contents.
    const char* const kBlock =
        "TRAJ_BEGIN 2\n"
        "0    0 0 0 0 0 0 0    0 0 0 0 0 0 0\n"
        "1.0  0 0 0 0 0 0 0    0 0 0 0 0 0 0\n"
        "TRAJ_END\n";

    void TestTrajectoryInputHandlesPartialAndCompletePipeLines()
    {
        int partial_pipe[2] = {-1, -1};
        Check(pipe(partial_pipe) == 0, "partial-line test creates a pipe");
        if (partial_pipe[0] >= 0 && partial_pipe[1] >= 0) {
            JointTrajectoryMailbox mailbox;
            std::atomic<bool> stop{false};
            std::atomic<bool> exited{false};
            std::thread reader([&] {
                RunTargetInput(mailbox, stop, partial_pipe[0]);
                exited.store(true, std::memory_order_release);
            });

            Check(WriteAll(partial_pipe[1], "TRAJ_BEGIN 2\n0    0 0 0"),
                  "partial line is written while the pipe stays open");
            Check(WaitForPipeDrain(partial_pipe[0], std::chrono::milliseconds(250)),
                  "reader consumes the partial line into its owned buffer");
            stop.store(true, std::memory_order_release);
            Check(WaitFor(exited, std::chrono::milliseconds(250)),
                  "input reader stops while a partial pipe line remains open");

            // Cleanup keeps a failing implementation from leaving a blocked
            // test thread behind: closing the writer supplies EOF.
            close(partial_pipe[1]);
            reader.join();
            close(partial_pipe[0]);
            Check(mailbox.Take() == nullptr,
                  "an incomplete block is never published");
        }

        int complete_pipe[2] = {-1, -1};
        Check(pipe(complete_pipe) == 0, "complete-line test creates a pipe");
        if (complete_pipe[0] >= 0 && complete_pipe[1] >= 0) {
            JointTrajectoryMailbox mailbox;
            std::atomic<bool> stop{false};
            std::atomic<bool> exited{false};
            std::thread reader([&] {
                RunTargetInput(mailbox, stop, complete_pipe[0]);
                exited.store(true, std::memory_order_release);
            });

            Check(WriteAll(complete_pipe[1], kBlock),
                  "a complete trajectory block is written to the pipe");
            close(complete_pipe[1]);
            Check(WaitFor(exited, std::chrono::milliseconds(250)),
                  "input reader exits after pipe EOF");
            reader.join();
            close(complete_pipe[0]);

            // Latest-wins single slot: one block in, one block out.
            Check(mailbox.Take() != nullptr,
                  "the complete block is validated and published");
        }
    }

    void TestPipeInputSurvivesWriterReconnect()
    {
        const std::string pipe_path = "./test_target_pipe_tmp";
        unlink(pipe_path.c_str());
        Check(mkfifo(pipe_path.c_str(), 0600) == 0, "mkfifo succeeds");

        JointTrajectoryMailbox mailbox;
        std::atomic<bool> stop{false};
        std::thread reader([&] {
            RunTargetInputFromPipe(mailbox, stop, pipe_path);
        });

        // Two independent writer sessions — the Stage 1 EOF failure mode.
        // The mailbox is latest-wins, so each block is collected before the
        // next writer opens; both must be seen despite the intervening EOF.
        int received = 0;
        for (int session = 0; session < 2; ++session) {
            {
                std::ofstream writer(pipe_path); // blocks until the reader opens
                Check(static_cast<bool>(writer), "writer opens pipe");
                writer << kBlock;
            }                                    // close = EOF for the reader
            for (int attempt = 0; attempt < 200; ++attempt) {
                if (mailbox.Take() != nullptr) { ++received; break; }
                std::this_thread::sleep_for(std::chrono::milliseconds(10));
            }
        }
        Check(received == 2, "blocks from both writer sessions arrive");

        stop.store(true);
        const auto join_start = std::chrono::steady_clock::now();
        reader.join();
        Check(std::chrono::steady_clock::now() - join_start
                  < std::chrono::seconds(1), "reader joins promptly on stop");
        unlink(pipe_path.c_str());
    }

} // namespace

int main()
{
    Check(UnitRamp(-0.1, 1.0) == 0.0, "null ramp clamps before start");
    Check(std::abs(UnitRamp(0.25, 1.0) - 0.25) < 1e-12,
          "null ramp scales linearly during startup");
    Check(UnitRamp(2.0, 1.0) == 1.0, "null ramp clamps after duration");
    TestRotationLog();
    TestTwistError();
    TestTaskTwistGating();
    TestDampedLeastSquares6();
    TestLimitAvoidance();
    TestPostureGuidance();
    TestDetailedSolveDecomposition();
    TestAgainstSimulationFixtures();
    TestTrajectoryInputHandlesPartialAndCompletePipeLines();
    TestPipeInputSurvivesWriterReconnect();

    if (failures == 0) {
        std::cout << "all reactive-law tests passed\n";
        return 0;
    }
    std::cout << failures << " failure(s)\n";
    return 1;
}
