//
// make_synthetic_log: write a SYNTHETIC log_format 6 run CSV, with no robot
// and no Kortex connection, so the telemetry schema and the plotting script
// can be exercised on a hardware-free machine.
//
// This deliberately drives the REAL LoopLog / LoopLogWriter / WriteCsvRow
// code the controller uses, rather than reimplementing the CSV layout. If
// the schema and the writer ever disagree, this tool fails with them.
//
// The scenario it fabricates is the one the 31 July 2026 runs showed
// (runs/2026-07-31/loop_log_20260731_1552*.csv): every joint's measured
// position frozen at one value while the integrated command walks away from
// it. Here it happens partway through a run that starts out tracking
// normally, so the plots show both the healthy and the frozen regime.
//
// THE OUTPUT IS NOT HARDWARE EVIDENCE. Every row is computed here. The
// preamble says so on its first line, and the filename carries the
// "SYNTHETIC" prefix so it cannot be mistaken for a run.
//
//   ./make_synthetic_log [output.csv]
//

#include "Hardware.h"

#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>

namespace
{
    constexpr int NUM_JOINTS = 7;
    constexpr double kDtS = 0.002;      // 500 Hz, config::kControlDtS
    constexpr double kLeadLimitDeg = 1.0; // config::kCommandLeadLimitDeg

    // Phases, in cycles. The hold streams a fixed setpoint; tracking moves
    // with the plant following; frozen keeps commanding while every
    // measurement and acknowledgement stops advancing.
    constexpr long kHoldCycles = 250;   // 0.5 s of pre-motion hold frames
    constexpr long kTrackCycles = 1500; // 3.0 s of healthy motion
    constexpr long kFrozenCycles = 1500; // 3.0 s of no response

    // A plausible start pose, degrees (shape taken from the 31 July logs so
    // the joint magnitudes look like this arm rather than zeros).
    constexpr double kStartDeg[NUM_JOINTS] = {
        279.702, 281.941, 30.0309, 19.4426, 4.60546, 341.332, 192.094
    };

    // Per-joint commanded rate during the moving phases, deg/s. Joints 3 and
    // 4 are the ones under review, so they get the clearest motion.
    constexpr double kRateDegS[NUM_JOINTS] = {
        0.8, -1.2, 4.0, -6.0, 0.5, 2.0, -0.3
    };
} // namespace

int main(int argc, char** argv)
{
    const std::string out_path =
        argc > 1 ? argv[1] : "SYNTHETIC_loop_log_format6.csv";

    std::ofstream csv(out_path);
    if (!csv)
    {
        std::cerr << "cannot write " << out_path << "\n";
        return 1;
    }

    // Preamble in the same '#' style as a real run, so every existing parser
    // skips it — but saying plainly what this file is.
    csv << "# SYNTHETIC DATA — NOT A ROBOT RUN. Generated by "
           "tools/make_synthetic_log.cpp with no hardware connected.\n"
        << "# Every row below is computed, not measured. Do not cite this "
           "file as evidence of robot behaviour.\n"
        << "# log_format = 6 (compiled)\n"
        << "# data_source = synthetic\n"
        << "# control_dt_s = " << kDtS << " (synthetic)\n"
        << "# command_lead_limit_deg = " << kLeadLimitDeg << " (synthetic)\n"
        << "# scenario = takeover hold, then healthy tracking, then every "
           "joint's feedback frozen while commands continue\n";

    LoopLog log(static_cast<std::size_t>(
        kHoldCycles + kTrackCycles + kFrozenCycles + 16));
    {
        LoopLogWriter writer(log, csv, std::chrono::milliseconds(5));

        // Command state carried across cycles, exactly as the integrator
        // carries it: degrees, continuous (never wrapped).
        double command_deg[NUM_JOINTS];
        double measured_deg[NUM_JOINTS];
        std::uint32_t ack[NUM_JOINTS];
        for (int i = 0; i < NUM_JOINTS; ++i)
        {
            command_deg[i] = kStartDeg[i];
            measured_deg[i] = kStartDeg[i];
            ack[i] = 1000u + static_cast<std::uint32_t>(i);
        }

        const long total = kHoldCycles + kTrackCycles + kFrozenCycles;
        for (long n = 0; n < total; ++n)
        {
            const bool holding = n < kHoldCycles;
            const bool frozen = n >= kHoldCycles + kTrackCycles;
            const double t_s = static_cast<double>(n) * kDtS;

            LoopLogSample s;
            s.t_s = t_s;
            s.dt_s = n == 0 ? kDtS : kDtS;
            s.t_send_s = t_s + 0.00008; // ~80 us of compute before the send
            s.t_recv_s = t_s + 0.00043; // ~350 us round trip
            s.cycle = holding ? 0 : (n - kHoldCycles + 1);
            s.refresh_ok = true;
            s.arm_state = 6; // ARMSTATE_SERVOING_LOW_LEVEL
            s.base_fault_bank = 0;
            s.command_frame_id = static_cast<std::uint32_t>(n + 1);
            s.feedback_frame_id = static_cast<std::uint32_t>(n + 1);

            for (int i = 0; i < NUM_JOINTS; ++i)
            {
                // What the controller asked for this cycle, before limits.
                const double requested_velocity_deg_s =
                    holding ? 0.0 : kRateDegS[i];
                const double requested_deg =
                    command_deg[i] + requested_velocity_deg_s * kDtS;

                // The lead limiter: never let the command sit further than
                // kLeadLimitDeg ahead of the measurement it is chasing.
                double sent_deg = requested_deg;
                bool limited = false;
                const double lead = requested_deg - measured_deg[i];
                if (std::abs(lead) > kLeadLimitDeg)
                {
                    sent_deg = measured_deg[i] +
                        std::copysign(kLeadLimitDeg, lead);
                    limited = true;
                }

                const double applied_velocity_deg_s =
                    (sent_deg - command_deg[i]) / kDtS;
                command_deg[i] = sent_deg;

                // The plant. While healthy it follows the command with a
                // one-cycle lag; once frozen it stops responding entirely
                // and its acknowledgement ID stops advancing with it.
                if (!frozen)
                {
                    measured_deg[i] += (sent_deg - measured_deg[i]) * 0.35;
                    ++ack[i];
                }

                s.requested_deg[i] = requested_deg;
                s.requested_velocity_deg_s[i] = requested_velocity_deg_s;
                s.commanded_deg[i] = sent_deg;
                s.commanded_velocity_deg_s[i] = applied_velocity_deg_s;
                s.lead_limited[i] = limited;
                s.measured_deg[i] = measured_deg[i];
                s.measured_raw_deg[i] =
                    measured_deg[i] - 360.0 * std::floor(measured_deg[i] / 360.0);
                s.velocity_deg_s[i] = frozen ? 0.0 : kRateDegS[i] * 0.35;
                s.torque_nm[i] = 0.0;
                s.fault_bank[i] = 0;
                s.actuator_command_ack[i] = ack[i];
                s.actuator_status_flags[i] = 0;
                s.actuator_jitter_us[i] = 12;
            }

            // The freshness counters, computed the way the Runner logs them:
            // consecutive cycles this joint's acknowledgement ID repeated.
            static std::uint32_t previous_ack[NUM_JOINTS] = {0};
            static int unchanged[NUM_JOINTS] = {0};
            static bool seeded = false;
            for (int i = 0; i < NUM_JOINTS; ++i)
            {
                if (!seeded)
                    unchanged[i] = 0;
                else if (ack[i] == previous_ack[i])
                    ++unchanged[i];
                else
                    unchanged[i] = 0;
                previous_ack[i] = ack[i];
                s.ack_unchanged_cycles[i] = unchanged[i];
            }
            seeded = true;

            log.push(s);
        }
        writer.Stop();
        std::cout << writer.rows_written() << " synthetic rows written\n";
    }

    // The same exit trailer main.cpp writes. A frozen plant no longer stops
    // the run by itself, so this synthetic session ends the only way it can:
    // the operator stops it.
    const double stop_t_s =
        static_cast<double>(kHoldCycles + kTrackCycles + kFrozenCycles - 1) * kDtS;
    csv << "# exit_reason = user_stop"
        << "\n# exit_time_s = " << stop_t_s
        << "\n# exit_cycle = " << (kTrackCycles + kFrozenCycles)
        << "\n# faults_observed = 0\n";
    csv.flush();

    std::cout << "SYNTHETIC log: " << out_path << "\n";
    return 0;
}
