"""Generate tests/frames_fixtures.h from the Python simulation frames.

Runs the ACTUAL simulation frame assembly (msc_project controller/frames.py
— the reference implementation, per the 2026-08-13 direction) on
deterministic pseudo-random inputs and emits inputs plus expected outputs
as a C++ header, so tests/test_frames.cpp can prove the C++ port computes
the same composition, Jacobian rotation, twist transport, and framed-target
resolution. Same technique and rules as gen_reactive_fixtures.py:
regenerate only when the simulation changes, the header is checked in.

    <msc_project>/.venv/bin/python scripts/gen_frames_fixtures.py

The C++ side does not own a robot model in these tests: the fixture records
the sim model's base-frame FK pose (T_B_E) and LOCAL_WORLD_ALIGNED Jacobian
(J_B) as INPUTS, so the test validates the assembly mathematics — which is
what the port reimplements — not the robot model, which hardware loads from
its own URDF.

Frame-name mapping (hardware ↦ sim): the sim's moving tracked body is the
torso T; on hardware it is the Vicon Mount segment MS. The maths is
identical; only the name changes.
"""

from pathlib import Path
import sys

MSC_PROJECT = Path.home() / "msc_project"
sys.path.insert(0, str(MSC_PROJECT))

import numpy as np
import pinocchio as pin

from controller import frames
from controller.state import (
    ArmJointState,
    FramedTarget,
    MountCalibration,
    PlantState,
    Pose,
    TargetFrame,
    Twist,
)

OUTPUT = Path(__file__).resolve().parent.parent / "tests" / "frames_fixtures.h"

rng = np.random.default_rng(20260813)


def random_rotation(scale=1.0):
    axis = rng.normal(size=3)
    axis /= np.linalg.norm(axis)
    return pin.exp3(scale * rng.uniform(0.2, 1.4) * axis)


def random_pose(translation_scale=1.0):
    return Pose(rng.uniform(-translation_scale, translation_scale, 3),
                random_rotation())


def fmt(values):
    return ", ".join(repr(float(v)) for v in np.asarray(values).ravel(order="C"))


def make_plant(q, qdot, torso_pose, torso_twist):
    arm = ArmJointState(q, qdot)
    return PlantState(
        sample_time_s=0.0,
        nominal_dt_s=0.002,
        torso_pose_world=torso_pose,
        torso_twist_world=torso_twist,
        right=arm,
        left=arm,
    )


lines = [
    "// GENERATED by scripts/gen_frames_fixtures.py from the ACTUAL",
    "// simulation frame assembly (msc_project controller/frames.py).",
    "// Do not edit; regenerate when the simulation changes.",
    "#pragma once",
    "",
    "namespace frames_fixtures {",
    "",
]

# ---- Case set A: arm_controller_state assembly -------------------------
state_cases = []
for index in range(6):
    q = rng.uniform(-1.5, 1.5, 7)
    qdot = rng.uniform(-0.8, 0.8, 7)
    torso_pose = random_pose(1.5)
    torso_twist = Twist(rng.uniform(-0.4, 0.4, 3), rng.uniform(-0.6, 0.6, 3))
    calibration_pose = random_pose(0.4)
    calibration = MountCalibration(calibration_pose, calibration_pose)

    plant = make_plant(q, qdot, torso_pose, torso_twist)
    out = frames.arm_controller_state(plant, "left", calibration)

    # The sim model's base-frame quantities, recorded as C++ INPUTS.
    pin.computeJointJacobians(frames.pin_model, frames.pin_data, q)
    pin.updateFramePlacements(frames.pin_model, frames.pin_data)
    T_B_E = frames.pin_data.oMf[frames.ee_frame_id].homogeneous.copy()
    J_B = pin.getFrameJacobian(
        frames.pin_model, frames.pin_data, frames.ee_frame_id,
        pin.LOCAL_WORLD_ALIGNED,
    )

    state_cases.append({
        "world_T_moving_p": torso_pose.position_m,
        "world_T_moving_R": torso_pose.rotation,
        "moving_T_base_p": calibration_pose.position_m,
        "moving_T_base_R": calibration_pose.rotation,
        "T_B_E": T_B_E,
        "J_B": J_B,
        "qdot": qdot,
        "moving_twist_lin": torso_twist.linear_m_s,
        "moving_twist_ang": torso_twist.angular_rad_s,
        "ee_pose_world_p": out.ee_pose_world.position_m,
        "ee_pose_world_R": out.ee_pose_world.rotation,
        "jacobian_world": out.jacobian_world,
        "ee_twist_world_lin": out.ee_twist_world.linear_m_s,
        "ee_twist_world_ang": out.ee_twist_world.angular_rad_s,
    })

lines.append(f"inline constexpr int kStateCaseCount = {len(state_cases)};")
for name, width in [
    ("world_T_moving_p", 3), ("world_T_moving_R", 9),
    ("moving_T_base_p", 3), ("moving_T_base_R", 9),
    ("T_B_E", 16), ("J_B", 42), ("qdot", 7),
    ("moving_twist_lin", 3), ("moving_twist_ang", 3),
    ("ee_pose_world_p", 3), ("ee_pose_world_R", 9),
    ("jacobian_world", 42),
    ("ee_twist_world_lin", 3), ("ee_twist_world_ang", 3),
]:
    rows = ",\n    ".join("{" + fmt(c[name]) + "}" for c in state_cases)
    lines.append(
        f"inline constexpr double k_{name}[kStateCaseCount][{width}] = {{\n    {rows}\n}};")
    lines.append("")

# ---- Case set B: resolve_target_world ----------------------------------
target_cases = []
for frame in (TargetFrame.WORLD, TargetFrame.TORSO, TargetFrame.BASE):
    for index in range(2):
        q = rng.uniform(-1.5, 1.5, 7)
        torso_pose = random_pose(1.5)
        torso_twist = Twist(rng.uniform(-0.4, 0.4, 3), rng.uniform(-0.6, 0.6, 3))
        calibration_pose = random_pose(0.4)
        calibration = MountCalibration(calibration_pose, calibration_pose)
        target = FramedTarget(
            frame,
            Pose(rng.uniform(-0.8, 0.8, 3), random_rotation()),
            Twist(rng.uniform(-0.3, 0.3, 3), rng.uniform(-0.3, 0.3, 3)),
        )
        plant = make_plant(q, np.zeros(7), torso_pose, torso_twist)
        resolved = frames.resolve_target_world(plant, "left", calibration, target)
        target_cases.append({
            "frame_id": {"world": 0, "torso": 1, "base": 2}[frame.value],
            "world_T_moving_p": torso_pose.position_m,
            "world_T_moving_R": torso_pose.rotation,
            "moving_T_base_p": calibration_pose.position_m,
            "moving_T_base_R": calibration_pose.rotation,
            "moving_twist_lin": torso_twist.linear_m_s,
            "moving_twist_ang": torso_twist.angular_rad_s,
            "target_p": target.pose.position_m,
            "target_R": target.pose.rotation,
            "target_twist_lin": target.twist.linear_m_s,
            "target_twist_ang": target.twist.angular_rad_s,
            "world_p": resolved.pose_world.position_m,
            "world_R": resolved.pose_world.rotation,
            "world_twist_lin": resolved.twist_world.linear_m_s,
            "world_twist_ang": resolved.twist_world.angular_rad_s,
        })

lines.append(f"inline constexpr int kTargetCaseCount = {len(target_cases)};")
frame_ids = ", ".join(str(c["frame_id"]) for c in target_cases)
lines.append(
    f"inline constexpr int k_target_frame[kTargetCaseCount] = {{{frame_ids}}};")
lines.append("")
for name, width in [
    ("world_T_moving_p", 3), ("world_T_moving_R", 9),
    ("moving_T_base_p", 3), ("moving_T_base_R", 9),
    ("moving_twist_lin", 3), ("moving_twist_ang", 3),
    ("target_p", 3), ("target_R", 9),
    ("target_twist_lin", 3), ("target_twist_ang", 3),
    ("world_p", 3), ("world_R", 9),
    ("world_twist_lin", 3), ("world_twist_ang", 3),
]:
    rows = ",\n    ".join("{" + fmt(c[name]) + "}" for c in target_cases)
    lines.append(
        f"inline constexpr double kT_{name}[kTargetCaseCount][{width}] = {{\n    {rows}\n}};")
    lines.append("")

lines.append("} // namespace frames_fixtures")
OUTPUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUTPUT} ({len(state_cases)} state cases, {len(target_cases)} target cases)")
