"""Generate tests/reactive_fixtures.h from the Python simulation law.

Runs the ACTUAL simulation controller (msc_project
controller/reactive_controller.py) on deterministic pseudo-random inputs and
emits the inputs plus expected outputs as a C++ header, so
tests/test_reactive_law.cpp can prove the C++ port computes the same
equations. Regenerate only when the simulation law itself changes:

    <msc_project>/.venv/bin/python scripts/gen_reactive_fixtures.py

The emitted header is checked in — the C++ tests must not depend on a
Python environment.

Tolerances: cases without null-space centering must agree to 1e-12 (the
equations are identical). The null-space case uses a loose 1e-6 because the
port deliberately damps the projector (the sim uses an undamped
pseudoinverse); the fixture sets dls_damping = 1e-8, where the two coincide
on a well-conditioned Jacobian — docs/decisions/reactive-pose-port.md.
"""

from pathlib import Path
import sys

MSC_PROJECT = Path.home() / "Projects" / "Code" / "msc_project"
sys.path.insert(0, str(MSC_PROJECT))

import numpy as np
import pinocchio as pin

from controller.reactive_controller import solve_reactive_velocity
from runtime_config import ReactivePoseConfig

OUTPUT = Path(__file__).resolve().parent.parent / "tests" / "reactive_fixtures.h"

rng = np.random.default_rng(20260723)


def random_rotation(angle):
    axis = rng.normal(size=3)
    axis /= np.linalg.norm(axis)
    return pin.exp3(angle * axis)


def fmt(values):
    # repr(float(...)): shortest exact round-trip text for a double — and
    # plain floats, not numpy's "np.float64(...)" repr.
    return ", ".join(repr(float(v)) for v in np.asarray(values).ravel(order="C"))


def make_config(**overrides):
    values = dict(
        kp_position_s_inv=1.0,
        kp_rotation_s_inv=1.0,
        kd_position=0.3,
        kd_rotation=0.3,
        null_gain_s_inv=0.0,
        dls_damping=0.1,
        position_enabled=True,
        orientation_enabled=True,
        velocity_enabled=False,
    )
    values.update(overrides)
    return ReactivePoseConfig(**values)


# --- RotationLog cases: R_err -> pin.log3(R_err), including near-pi ---------
log_cases = []
for angle in (0.0, 1e-9, 0.3, 1.2, 2.5, 3.0, 3.14159):
    rotation = random_rotation(angle)
    log_cases.append((rotation, pin.log3(rotation)))

# --- solve_reactive_velocity cases ------------------------------------------
# Mask matches config::kNullCenteringMask (continuous joints never center).
MASK = np.array([0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0])
MID = np.zeros(7)

solve_cases = []


def add_case(name, config, null_gain, tolerance, jacobian_scale=1.0):
    jacobian = jacobian_scale * rng.uniform(-1.0, 1.0, size=(6, 7))
    e_pos = rng.uniform(-0.05, 0.05, size=3)
    e_rot = rng.uniform(-0.2, 0.2, size=3)
    e_v = rng.uniform(-0.05, 0.05, size=3)
    e_w = rng.uniform(-0.1, 0.1, size=3)
    q = rng.uniform(-2.0, 2.0, size=7)  # |q - mid| < pi: wrap is a no-op
    solve = solve_reactive_velocity(
        jacobian, e_pos, e_rot, e_v, e_w, q, MID, null_gain * MASK, config
    )
    solve_cases.append(
        dict(
            name=name,
            jacobian=jacobian,
            e_pos=e_pos,
            e_rot=e_rot,
            e_v=e_v,
            e_w=e_w,
            q=q,
            config=config,
            null_gain=null_gain,
            null_enabled=null_gain != 0.0,
            tolerance=tolerance,
            expected=solve.qdot_raw,
        )
    )


add_case("p_only", make_config(), null_gain=0.0, tolerance=1e-12)
add_case(
    "pd",
    make_config(velocity_enabled=True),
    null_gain=0.0,
    tolerance=1e-12,
)
add_case(
    "position_term_disabled",
    make_config(position_enabled=False),
    null_gain=0.0,
    tolerance=1e-12,
)
add_case(
    "orientation_term_disabled",
    make_config(orientation_enabled=False),
    null_gain=0.0,
    tolerance=1e-12,
)
add_case(
    "near_singular",
    make_config(),
    null_gain=0.0,
    tolerance=1e-12,
    jacobian_scale=1e-6,
)
add_case(
    "null_space_tiny_damping",
    make_config(dls_damping=1e-8),
    null_gain=1.0,
    tolerance=1e-6,
)

# --- emit -------------------------------------------------------------------
lines = [
    "// Generated by scripts/gen_reactive_fixtures.py from the Python",
    "// simulation law (msc_project controller/reactive_controller.py).",
    "// DO NOT EDIT — regenerate with the script if the simulation changes.",
    "",
    "#ifndef HUMANSL_MASTERS_PROJECT_2025_REACTIVE_FIXTURES_H",
    "#define HUMANSL_MASTERS_PROJECT_2025_REACTIVE_FIXTURES_H",
    "",
    "namespace fixtures",
    "{",
    "",
    "    struct RotationLogCase {",
    "        double rotation[9]; // row-major",
    "        double expected[3];",
    "    };",
    "",
    f"    inline constexpr RotationLogCase kRotationLogCases[{len(log_cases)}] = {{",
]
for rotation, expected in log_cases:
    lines.append(f"        {{{{{fmt(rotation)}}},")
    lines.append(f"         {{{fmt(expected)}}}}},")
lines += [
    "    };",
    "",
    "    struct SolveCase {",
    "        const char* name;",
    "        double jacobian[42]; // row-major 6x7",
    "        double e_pos[3];",
    "        double e_rot[3];",
    "        double e_v[3];",
    "        double e_w[3];",
    "        double q[7];",
    "        double kp_position_s_inv;",
    "        double kp_rotation_s_inv;",
    "        double kd_position;",
    "        double kd_rotation;",
    "        double null_gain_s_inv;",
    "        double dls_lambda;",
    "        bool position_enabled;",
    "        bool orientation_enabled;",
    "        bool velocity_enabled;",
    "        bool null_space_enabled;",
    "        double tolerance;",
    "        double expected[7];",
    "    };",
    "",
    f"    inline constexpr SolveCase kSolveCases[{len(solve_cases)}] = {{",
]
for case in solve_cases:
    config = case["config"]
    bools = ", ".join(
        "true" if flag else "false"
        for flag in (
            config.position_enabled,
            config.orientation_enabled,
            config.velocity_enabled,
            case["null_enabled"],
        )
    )
    lines += [
        f"        {{\"{case['name']}\",",
        f"         {{{fmt(case['jacobian'])}}},",
        f"         {{{fmt(case['e_pos'])}}}, {{{fmt(case['e_rot'])}}},",
        f"         {{{fmt(case['e_v'])}}}, {{{fmt(case['e_w'])}}},",
        f"         {{{fmt(case['q'])}}},",
        f"         {config.kp_position_s_inv!r}, {config.kp_rotation_s_inv!r},",
        f"         {config.kd_position!r}, {config.kd_rotation!r},",
        f"         {case['null_gain']!r}, {config.dls_damping!r},",
        f"         {bools},",
        f"         {case['tolerance']!r},",
        f"         {{{fmt(case['expected'])}}}}},",
    ]
lines += [
    "    };",
    "",
    "} // namespace fixtures",
    "",
    "#endif // HUMANSL_MASTERS_PROJECT_2025_REACTIVE_FIXTURES_H",
    "",
]

OUTPUT.write_text("\n".join(lines))
print(f"wrote {OUTPUT} ({len(log_cases)} rotation cases, {len(solve_cases)} solve cases)")
