//
// Frames — world-frame state assembly and framed-target resolution, ported
// function-for-function from msc_project controller/frames.py, which is the
// REFERENCE IMPLEMENTATION of world-frame control for this project
// (Christian's direction, 2026-08-13; spec
// docs/superpowers/specs/2026-08-13-world-hold-slice-design.md).
// tests/test_frames.cpp proves the port against fixtures generated by
// running the actual simulation (scripts/gen_frames_fixtures.py).
//
// Frame-name mapping (hardware ↦ sim): the sim's moving tracked body is
// the torso T (MuJoCo ground truth); on hardware it is the Vicon Mount
// segment MS. Every equation is identical under that renaming, so the
// parameters here say "moving" and each call site names its frames.
//
// Unlike frames.py these functions do not own a robot model: the caller
// supplies the base-frame FK pose (T_B_E) and LOCAL_WORLD_ALIGNED Jacobian
// (J_B) from Kinematics. That is the one deliberate signature difference —
// the assembly mathematics, which is what the fixtures pin, is unchanged.
//
// Pure Eigen, header-only, no allocation beyond fixed-size values. Nothing
// here reads sensors or owns freshness policy — Runner and
// CartesianReference provide the coherent state and clock decision.
//

#pragma once

#include <algorithm>
#include <cmath>

#include <Eigen/Dense>
#include <Eigen/Geometry>

#include "State.h" // Twist

namespace world_frames {

// A stale sample retains the last trustworthy measured Mount twist, decayed
// from the freshness boundary. Computing from absolute sample age avoids a
// loop-rate-dependent result when one cycle is delayed or skipped.
inline double StaleTwistDecayMultiplier(double sample_age_s,
                                        double fresh_max_age_s,
                                        double tau_s)
{
    // fresh_max_age_s and tau_s are proven finite and positive by
    // ValidateExecutionConfig; only the sample age arrives from Vicon.
    if (!std::isfinite(sample_age_s))
        return 0.0;
    const double stale_age_s =
        std::max(0.0, sample_age_s - fresh_max_age_s);
    if (stale_age_s == 0.0)
        return 1.0;
    return std::exp(-stale_age_s / tau_s);
}

// Vicon can continue delivering low-age frames while the Mount segment alone
// is invalid. Control-time staleness covers that case; source age covers a
// delayed cycle or complete stream loss. Taking the maximum prevents either
// clock from making stale motion look newer than it is.
inline double EffectiveStaleDurationS(double sample_age_s,
                                      double stale_elapsed_s,
                                      double fresh_max_age_s)
{
    // stale_elapsed_s is accumulated internally from the control step and
    // fresh_max_age_s is config-validated; only the sample age is external.
    const double beyond_age = std::isfinite(sample_age_s)
        ? std::max(0.0, sample_age_s - fresh_max_age_s)
        : 0.0;
    return std::max(stale_elapsed_s, beyond_age);
}

// State.h owns the shared fixed-size pose value; this name preserves the
// simulation port's vocabulary without creating a second representation.
using FramePose = CartesianPose;

// frames.py compose_pose: parent_to_child ∘ child_to_object.
inline FramePose ComposePose(const FramePose& parent_to_child,
                             const FramePose& child_to_object)
{
    FramePose out;
    out.position_m = parent_to_child.position_m +
                     parent_to_child.rotation * child_to_object.position_m;
    out.rotation = parent_to_child.rotation * child_to_object.rotation;
    return out;
}

// What frames.py's arm_controller_state returns, minus the safety points
// (the human-safety filter is not ported in this slice): the end-effector
// pose, Jacobian, and measured twist, all expressed in the WORLD frame.
struct WorldArmState {
    FramePose ee_pose_world;
    Eigen::Matrix<double, 6, 7> jacobian_world =
        Eigen::Matrix<double, 6, 7>::Zero();
    Twist ee_twist_world;
};

// frames.py arm_controller_state (:120), inputs made explicit:
//   world_T_moving — the tracked body's pose in world (sim: torso from
//                    MuJoCo; hardware: Mount segment from Vicon, ZOH)
//   moving_T_base  — the fixed model transform (sim: MountCalibration;
//                    hardware: mount_T_base, with tracked Mount segment
//                    currently assumed coincident with model Mount)
//   T_B_E, J_B     — FK pose and LOCAL_WORLD_ALIGNED Jacobian in base axes
//   qdot_rad_s     — measured joint velocities
//   moving_twist_world — the tracked body's world twist (sim: ground
//                    truth; hardware: filtered Vicon Mount twist)
inline WorldArmState
ArmControllerState(const FramePose& world_T_moving,
                   const FramePose& moving_T_base,
                   const FramePose& T_B_E,
                   const Eigen::Matrix<double, 6, 7>& J_B,
                   const Eigen::Matrix<double, 7, 1>& qdot_rad_s,
                   const Twist& moving_twist_world)
{
    WorldArmState out;

    // T_W_B = T_W_moving · T_moving_B, then ee = T_W_B · T_B_E.
    const FramePose world_T_base = ComposePose(world_T_moving, moving_T_base);
    out.ee_pose_world = ComposePose(world_T_base, T_B_E);

    // J^W: both row blocks rotated by R_W_B (frames.py:147-150).
    const Eigen::Matrix3d R_W_B = world_T_base.rotation;
    out.jacobian_world.topRows<3>() = R_W_B * J_B.topRows<3>();
    out.jacobian_world.bottomRows<3>() = R_W_B * J_B.bottomRows<3>();

    // Twist transport (frames.py:154-161): the moving body's twist carried
    // to the end-effector point — offset from the MOVING body's origin —
    // plus the arm's own contribution J^W q̇.
    const Eigen::Matrix<double, 6, 1> arm_twist =
        out.jacobian_world * qdot_rad_s;
    const Eigen::Vector3d offset_world =
        out.ee_pose_world.position_m - world_T_moving.position_m;
    out.ee_twist_world.linear_m_s =
        moving_twist_world.linear_m_s +
        moving_twist_world.angular_rad_s.cross(offset_world) +
        arm_twist.head<3>();
    out.ee_twist_world.angular_rad_s =
        moving_twist_world.angular_rad_s + arm_twist.tail<3>();
    return out;
}

// frames.py TargetFrame: which frame a configured target is declared in.
// "Moving" is the sim's TORSO (hardware: the Mount segment); "Base" is the
// arm's base_link reached through the calibration.
enum class TargetFrame { kWorld = 0, kMoving = 1, kBase = 2 };

// A target pose + feed-forward twist in its declared frame (sim
// FramedTarget), and the same resolved to world (sim WorldTarget).
struct WorldTargetValue {
    FramePose pose_world;
    Twist twist_world;
};

// frames.py _world_reference_frame (:179) + resolve_target_world (:223):
// convert a framed target to world ONCE PER CYCLE from the current moving
// pose. Controllers receive only the result and never see the frame
// selector — the sim's boundary rule, kept on hardware.
inline WorldTargetValue
ResolveTargetWorld(const FramePose& world_T_moving,
                   const FramePose& moving_T_base,
                   const Twist& moving_twist_world, TargetFrame frame,
                   const FramePose& target_pose, const Twist& target_twist)
{
    // World pose/twist of the declared reference frame.
    FramePose frame_pose; // world frame: identity
    Twist frame_twist;    // world frame: zero
    if (frame == TargetFrame::kMoving) {
        frame_pose = world_T_moving;
        frame_twist = moving_twist_world;
    } else if (frame == TargetFrame::kBase) {
        frame_pose = ComposePose(world_T_moving, moving_T_base);
        const Eigen::Vector3d offset_world =
            frame_pose.position_m - world_T_moving.position_m;
        frame_twist.linear_m_s =
            moving_twist_world.linear_m_s +
            moving_twist_world.angular_rad_s.cross(offset_world);
        frame_twist.angular_rad_s = moving_twist_world.angular_rad_s;
    }

    WorldTargetValue out;
    out.pose_world = ComposePose(frame_pose, target_pose);
    const Eigen::Vector3d offset_world =
        frame_pose.rotation * target_pose.position_m;
    out.twist_world.linear_m_s =
        frame_twist.linear_m_s +
        frame_twist.angular_rad_s.cross(offset_world) +
        frame_pose.rotation * target_twist.linear_m_s;
    out.twist_world.angular_rad_s =
        frame_twist.angular_rad_s +
        frame_pose.rotation * target_twist.angular_rad_s;
    return out;
}

} // namespace world_frames
