//
// Frames port cross-validation: src/Frames.h against fixtures generated by
// RUNNING the simulation's frames.py (scripts/gen_frames_fixtures.py) —
// the same technique test_reactive_law.cpp uses for the law. The sim is
// the reference implementation; agreement here is the evidence that the
// hardware assembly computes the simulation's mathematics, not a
// re-derivation. Tolerance 1e-12: the equations are identical.
//
// Hardware-free: pure Eigen, no model, no SDK, no Kortex.
//

#include <cmath>
#include <iostream>
#include <string>

#include "Frames.h"
#include "frames_fixtures.h"

namespace
{
    int failures = 0;

    void Check(bool ok, const std::string& what)
    {
        if (!ok) {
            std::cout << "FAIL: " << what << "\n";
            ++failures;
        }
    }

    Eigen::Vector3d Vec3(const double* v)
    {
        return {v[0], v[1], v[2]};
    }

    Eigen::Matrix3d Mat3(const double* v) // row-major in the fixture
    {
        Eigen::Matrix3d m;
        for (int r = 0; r < 3; ++r)
            for (int c = 0; c < 3; ++c)
                m(r, c) = v[3 * r + c];
        return m;
    }

    world_frames::FramePose PoseOf(const double* p, const double* R)
    {
        return {Vec3(p), Mat3(R)};
    }

    bool Near(const Eigen::MatrixXd& a, const Eigen::MatrixXd& b,
              double tol = 1e-12)
    {
        return (a - b).cwiseAbs().maxCoeff() <= tol;
    }
} // namespace

int main()
{
    using namespace frames_fixtures;

    // --- arm_controller_state assembly against the sim
    for (int i = 0; i < kStateCaseCount; ++i) {
        const std::string tag = "state case " + std::to_string(i) + ": ";

        // T_B_E arrives as a row-major 4x4 homogeneous matrix.
        world_frames::FramePose T_B_E;
        for (int r = 0; r < 3; ++r) {
            for (int c = 0; c < 3; ++c)
                T_B_E.rotation(r, c) = k_T_B_E[i][4 * r + c];
            T_B_E.position_m[r] = k_T_B_E[i][4 * r + 3];
        }
        Eigen::Matrix<double, 6, 7> J_B; // row-major 6x7 in the fixture
        for (int r = 0; r < 6; ++r)
            for (int c = 0; c < 7; ++c)
                J_B(r, c) = k_J_B[i][7 * r + c];
        Eigen::Matrix<double, 7, 1> qdot;
        for (int j = 0; j < 7; ++j)
            qdot[j] = k_qdot[i][j];
        Twist moving_twist;
        moving_twist.linear_m_s = Vec3(k_moving_twist_lin[i]);
        moving_twist.angular_rad_s = Vec3(k_moving_twist_ang[i]);

        const world_frames::WorldArmState out =
            world_frames::ArmControllerState(
                PoseOf(k_world_T_moving_p[i], k_world_T_moving_R[i]),
                PoseOf(k_moving_T_base_p[i], k_moving_T_base_R[i]), T_B_E,
                J_B, qdot, moving_twist);

        Check(Near(out.ee_pose_world.position_m, Vec3(k_ee_pose_world_p[i])),
              tag + "ee world position matches the sim");
        Check(Near(out.ee_pose_world.rotation, Mat3(k_ee_pose_world_R[i])),
              tag + "ee world rotation matches the sim");
        Eigen::Matrix<double, 6, 7> J_W_expected;
        for (int r = 0; r < 6; ++r)
            for (int c = 0; c < 7; ++c)
                J_W_expected(r, c) = k_jacobian_world[i][7 * r + c];
        Check(Near(out.jacobian_world, J_W_expected),
              tag + "world Jacobian matches the sim");
        Check(Near(out.ee_twist_world.linear_m_s,
                   Vec3(k_ee_twist_world_lin[i])),
              tag + "world twist (linear, with transport) matches the sim");
        Check(Near(out.ee_twist_world.angular_rad_s,
                   Vec3(k_ee_twist_world_ang[i])),
              tag + "world twist (angular) matches the sim");
    }

    // --- resolve_target_world against the sim, all three frames
    for (int i = 0; i < kTargetCaseCount; ++i) {
        const std::string tag = "target case " + std::to_string(i) + ": ";
        Twist moving_twist;
        moving_twist.linear_m_s = Vec3(kT_moving_twist_lin[i]);
        moving_twist.angular_rad_s = Vec3(kT_moving_twist_ang[i]);
        Twist target_twist;
        target_twist.linear_m_s = Vec3(kT_target_twist_lin[i]);
        target_twist.angular_rad_s = Vec3(kT_target_twist_ang[i]);

        const world_frames::WorldTargetValue out =
            world_frames::ResolveTargetWorld(
                PoseOf(kT_world_T_moving_p[i], kT_world_T_moving_R[i]),
                PoseOf(kT_moving_T_base_p[i], kT_moving_T_base_R[i]),
                moving_twist,
                static_cast<world_frames::TargetFrame>(k_target_frame[i]),
                PoseOf(kT_target_p[i], kT_target_R[i]), target_twist);

        Check(Near(out.pose_world.position_m, Vec3(kT_world_p[i])),
              tag + "world target position matches the sim");
        Check(Near(out.pose_world.rotation, Mat3(kT_world_R[i])),
              tag + "world target rotation matches the sim");
        Check(Near(out.twist_world.linear_m_s, Vec3(kT_world_twist_lin[i])),
              tag + "world target twist (linear) matches the sim");
        Check(Near(out.twist_world.angular_rad_s,
                   Vec3(kT_world_twist_ang[i])),
              tag + "world target twist (angular) matches the sim");
    }

    if (failures == 0) {
        std::cout << "test_frames: all checks passed ("
                  << kStateCaseCount << " state + " << kTargetCaseCount
                  << " target cases vs the simulation)\n";
        return 0;
    }
    std::cout << "test_frames: " << failures << " check(s) failed\n";
    return 1;
}
